package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EntityListeners;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AgentInboxViewId generated by hbm2java
 */
@Embeddable
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AgentInboxViewId implements java.io.Serializable {

	private String caseid;
	private int caseId;
	private String insuredName;
	private String insuredContact;
	private String planCode;
	private String planName;
	private String productCode;
	private String productName;
	private String faceAmount;
	private BigDecimal amountCollected;
	private String casetypecd;
	private Date signedDate;
	private Integer daysLeftToSubmit;
	private String applncasetypecd;
	private Integer companyid;
	private String companyCode;
	private String companyName;
	private String lstUpdtUserId;
	private String caseStatus;

	public AgentInboxViewId() {
	}

	public AgentInboxViewId(int caseId, String caseStatus) {
		this.caseId = caseId;
		this.caseStatus = caseStatus;
	}

	public AgentInboxViewId(String caseid, int caseId, String insuredName, String insuredContact, String planCode,
			String planName, String productCode, String productName, String faceAmount, BigDecimal amountCollected,
			String casetypecd, Date signedDate, Integer daysLeftToSubmit, String applncasetypecd, Integer companyid,
			String companyCode, String companyName, String lstUpdtUserId, String caseStatus) {
		this.caseid = caseid;
		this.caseId = caseId;
		this.insuredName = insuredName;
		this.insuredContact = insuredContact;
		this.planCode = planCode;
		this.planName = planName;
		this.productCode = productCode;
		this.productName = productName;
		this.faceAmount = faceAmount;
		this.amountCollected = amountCollected;
		this.casetypecd = casetypecd;
		this.signedDate = signedDate;
		this.daysLeftToSubmit = daysLeftToSubmit;
		this.applncasetypecd = applncasetypecd;
		this.companyid = companyid;
		this.companyCode = companyCode;
		this.companyName = companyName;
		this.lstUpdtUserId = lstUpdtUserId;
		this.caseStatus = caseStatus;
	}

	@Column(name = "CASEID", length = 21)
	public String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(String caseid) {
		this.caseid = caseid;
	}

	@Column(name = "CASE_ID", nullable = false)
	public int getCaseId() {
		return this.caseId;
	}

	public void setCaseId(int caseId) {
		this.caseId = caseId;
	}

	@Column(name = "INSURED_NAME", length = 101)
	public String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(String insuredName) {
		this.insuredName = insuredName;
	}

	@Column(name = "INSURED_CONTACT", length = 100)
	public String getInsuredContact() {
		return this.insuredContact;
	}

	public void setInsuredContact(String insuredContact) {
		this.insuredContact = insuredContact;
	}

	@Column(name = "PLAN_CODE", length = 15)
	public String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	@Column(name = "PLAN_NAME", length = 250)
	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	@Column(name = "PRODUCT_CODE", length = 8)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "PRODUCT_NAME", length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "FACE_AMOUNT", length = 8000)
	public String getFaceAmount() {
		return this.faceAmount;
	}

	public void setFaceAmount(String faceAmount) {
		this.faceAmount = faceAmount;
	}

	@Column(name = "AMOUNT_COLLECTED", precision = 12)
	public BigDecimal getAmountCollected() {
		return this.amountCollected;
	}

	public void setAmountCollected(BigDecimal amountCollected) {
		this.amountCollected = amountCollected;
	}

	@Column(name = "CASETYPECD", length = 20)
	public String getCasetypecd() {
		return this.casetypecd;
	}

	public void setCasetypecd(String casetypecd) {
		this.casetypecd = casetypecd;
	}

	@Column(name = "SIGNED_DATE", length = 23)
	public Date getSignedDate() {
		return this.signedDate;
	}

	public void setSignedDate(Date signedDate) {
		this.signedDate = signedDate;
	}

	@Column(name = "DAYS_LEFT_TO_SUBMIT")
	public Integer getDaysLeftToSubmit() {
		return this.daysLeftToSubmit;
	}

	public void setDaysLeftToSubmit(Integer daysLeftToSubmit) {
		this.daysLeftToSubmit = daysLeftToSubmit;
	}

	@Column(name = "APPLNCASETYPECD", length = 20)
	public String getApplncasetypecd() {
		return this.applncasetypecd;
	}

	public void setApplncasetypecd(String applncasetypecd) {
		this.applncasetypecd = applncasetypecd;
	}

	@Column(name = "COMPANYID")
	public Integer getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(Integer companyid) {
		this.companyid = companyid;
	}

	@Column(name = "COMPANY_CODE", length = 8)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "COMPANY_NAME", length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "LST_UPDT_USER_ID", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@Column(name = "CASE_STATUS", nullable = true, length = 20)
	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgentInboxViewId))
			return false;
		AgentInboxViewId castOther = (AgentInboxViewId) other;

		return ((this.getCaseid() == castOther.getCaseid()) || (this.getCaseid() != null
				&& castOther.getCaseid() != null && this.getCaseid().equals(castOther.getCaseid())))
				&& (this.getCaseId() == castOther.getCaseId())
				&& ((this.getInsuredName() == castOther.getInsuredName())
						|| (this.getInsuredName() != null && castOther.getInsuredName() != null
								&& this.getInsuredName().equals(castOther.getInsuredName())))
				&& ((this.getInsuredContact() == castOther.getInsuredContact())
						|| (this.getInsuredContact() != null && castOther.getInsuredContact() != null
								&& this.getInsuredContact().equals(castOther.getInsuredContact())))
				&& ((this.getPlanCode() == castOther.getPlanCode()) || (this.getPlanCode() != null
						&& castOther.getPlanCode() != null && this.getPlanCode().equals(castOther.getPlanCode())))
				&& ((this.getPlanName() == castOther.getPlanName()) || (this.getPlanName() != null
						&& castOther.getPlanName() != null && this.getPlanName().equals(castOther.getPlanName())))
				&& ((this.getProductCode() == castOther.getProductCode())
						|| (this.getProductCode() != null && castOther.getProductCode() != null
								&& this.getProductCode().equals(castOther.getProductCode())))
				&& ((this.getProductName() == castOther.getProductName())
						|| (this.getProductName() != null && castOther.getProductName() != null
								&& this.getProductName().equals(castOther.getProductName())))
				&& ((this.getFaceAmount() == castOther.getFaceAmount()) || (this.getFaceAmount() != null
						&& castOther.getFaceAmount() != null && this.getFaceAmount().equals(castOther.getFaceAmount())))
				&& ((this.getAmountCollected() == castOther.getAmountCollected())
						|| (this.getAmountCollected() != null && castOther.getAmountCollected() != null
								&& this.getAmountCollected().equals(castOther.getAmountCollected())))
				&& ((this.getCasetypecd() == castOther.getCasetypecd()) || (this.getCasetypecd() != null
						&& castOther.getCasetypecd() != null && this.getCasetypecd().equals(castOther.getCasetypecd())))
				&& ((this.getSignedDate() == castOther.getSignedDate()) || (this.getSignedDate() != null
						&& castOther.getSignedDate() != null && this.getSignedDate().equals(castOther.getSignedDate())))
				&& ((this.getDaysLeftToSubmit() == castOther.getDaysLeftToSubmit())
						|| (this.getDaysLeftToSubmit() != null && castOther.getDaysLeftToSubmit() != null
								&& this.getDaysLeftToSubmit().equals(castOther.getDaysLeftToSubmit())))
				&& ((this.getApplncasetypecd() == castOther.getApplncasetypecd())
						|| (this.getApplncasetypecd() != null && castOther.getApplncasetypecd() != null
								&& this.getApplncasetypecd().equals(castOther.getApplncasetypecd())))
				&& ((this.getCompanyid() == castOther.getCompanyid()) || (this.getCompanyid() != null
						&& castOther.getCompanyid() != null && this.getCompanyid().equals(castOther.getCompanyid())))
				&& ((this.getCompanyCode() == castOther.getCompanyCode())
						|| (this.getCompanyCode() != null && castOther.getCompanyCode() != null
								&& this.getCompanyCode().equals(castOther.getCompanyCode())))
				&& ((this.getCompanyName() == castOther.getCompanyName())
						|| (this.getCompanyName() != null && castOther.getCompanyName() != null
								&& this.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getLstUpdtUserId() == castOther.getLstUpdtUserId())
						|| (this.getLstUpdtUserId() != null && castOther.getLstUpdtUserId() != null
								&& this.getLstUpdtUserId().equals(castOther.getLstUpdtUserId())))
				&& ((this.getCaseStatus() == castOther.getCaseStatus())
						|| (this.getCaseStatus() != null && castOther.getCaseStatus() != null
								&& this.getCaseStatus().equals(castOther.getCaseStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCaseid() == null ? 0 : this.getCaseid().hashCode());
		result = 37 * result + this.getCaseId();
		result = 37 * result + (getInsuredName() == null ? 0 : this.getInsuredName().hashCode());
		result = 37 * result + (getInsuredContact() == null ? 0 : this.getInsuredContact().hashCode());
		result = 37 * result + (getPlanCode() == null ? 0 : this.getPlanCode().hashCode());
		result = 37 * result + (getPlanName() == null ? 0 : this.getPlanName().hashCode());
		result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
		result = 37 * result + (getProductName() == null ? 0 : this.getProductName().hashCode());
		result = 37 * result + (getFaceAmount() == null ? 0 : this.getFaceAmount().hashCode());
		result = 37 * result + (getAmountCollected() == null ? 0 : this.getAmountCollected().hashCode());
		result = 37 * result + (getCasetypecd() == null ? 0 : this.getCasetypecd().hashCode());
		result = 37 * result + (getSignedDate() == null ? 0 : this.getSignedDate().hashCode());
		result = 37 * result + (getDaysLeftToSubmit() == null ? 0 : this.getDaysLeftToSubmit().hashCode());
		result = 37 * result + (getApplncasetypecd() == null ? 0 : this.getApplncasetypecd().hashCode());
		result = 37 * result + (getCompanyid() == null ? 0 : this.getCompanyid().hashCode());
		result = 37 * result + (getCompanyCode() == null ? 0 : this.getCompanyCode().hashCode());
		result = 37 * result + (getCompanyName() == null ? 0 : this.getCompanyName().hashCode());
		result = 37 * result + (getLstUpdtUserId() == null ? 0 : this.getLstUpdtUserId().hashCode());
		result = 37 * result + (getCaseStatus() == null ? 0 : this.getCaseStatus().hashCode());
		return result;
	}

}
