package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * AgentT generated by hbm2java
 */
@Entity
@Table(name = "agent_t")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AgentT implements java.io.Serializable {

	private Integer agentSeqNum;
	private String agentCd;
	private String firstName;
	private String middleName;
	private String lastName;
	private String addrLine1;
	private String addrLine2;
	private String city;
	private String state;
	private String zip;
	private String country;
	private String carrierApptTypCd;
	private String carrierApptStatus;
	private String appointmentCategory;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private Set<AgentAssociationT> agentAssociationTs = new HashSet<AgentAssociationT>(0);
	private Set<AgentPhoneT> agentPhoneTs = new HashSet<AgentPhoneT>(0);

	public AgentT() {
	}

	public AgentT(String agentCd, char isDeletedInd, Date lstUpdtDtm) {
		this.agentCd = agentCd;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public AgentT(String agentCd, String firstName, String middleName, String lastName, String addrLine1,
			String addrLine2, String city, String state, String zip, String country, String carrierApptTypCd,
			String carrierApptStatus, String appointmentCategory, char isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm, Set<AgentAssociationT> agentAssociationTs, Set<AgentPhoneT> agentPhoneTs) {
		this.agentCd = agentCd;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.addrLine1 = addrLine1;
		this.addrLine2 = addrLine2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.carrierApptTypCd = carrierApptTypCd;
		this.carrierApptStatus = carrierApptStatus;
		this.appointmentCategory = appointmentCategory;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.agentAssociationTs = agentAssociationTs;
		this.agentPhoneTs = agentPhoneTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "agent_seq_num", unique = true, nullable = false)
	public Integer getAgentSeqNum() {
		return this.agentSeqNum;
	}

	public void setAgentSeqNum(Integer agentSeqNum) {
		this.agentSeqNum = agentSeqNum;
	}

	@Column(name = "agent_cd", nullable = false, length = 15)
	public String getAgentCd() {
		return this.agentCd;
	}

	public void setAgentCd(String agentCd) {
		this.agentCd = agentCd;
	}

	@Column(name = "first_name", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 8)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "addr_line_1", length = 100)
	public String getAddrLine1() {
		return this.addrLine1;
	}

	public void setAddrLine1(String addrLine1) {
		this.addrLine1 = addrLine1;
	}

	@Column(name = "addr_line_2", length = 100)
	public String getAddrLine2() {
		return this.addrLine2;
	}

	public void setAddrLine2(String addrLine2) {
		this.addrLine2 = addrLine2;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip", length = 9)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "carrier_appt_typ_cd", length = 25)
	public String getCarrierApptTypCd() {
		return this.carrierApptTypCd;
	}

	public void setCarrierApptTypCd(String carrierApptTypCd) {
		this.carrierApptTypCd = carrierApptTypCd;
	}

	@Column(name = "carrier_appt_status", length = 8)
	public String getCarrierApptStatus() {
		return this.carrierApptStatus;
	}

	public void setCarrierApptStatus(String carrierApptStatus) {
		this.carrierApptStatus = carrierApptStatus;
	}

	@Column(name = "appointment_category", length = 8)
	public String getAppointmentCategory() {
		return this.appointmentCategory;
	}

	public void setAppointmentCategory(String appointmentCategory) {
		this.appointmentCategory = appointmentCategory;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentT")
	public Set<AgentAssociationT> getAgentAssociationTs() {
		return this.agentAssociationTs;
	}

	public void setAgentAssociationTs(Set<AgentAssociationT> agentAssociationTs) {
		this.agentAssociationTs = agentAssociationTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentT")
	public Set<AgentPhoneT> getAgentPhoneTs() {
		return this.agentPhoneTs;
	}

	public void setAgentPhoneTs(Set<AgentPhoneT> agentPhoneTs) {
		this.agentPhoneTs = agentPhoneTs;
	}

}
