package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * AppCasePlanSpecificFields generated by hbm2java
 */
@Entity
@Table(name = "app_case_plan_specific_fields")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AppCasePlanSpecificFields implements java.io.Serializable {

	private Integer appCasePlanSpecificFieldId;
	private AppCase appCase;
	private Integer planSpecFieldId;
	private String planSpecFieldValue;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public AppCasePlanSpecificFields() {
	}

	public AppCasePlanSpecificFields(char isDeletedInd, Date lstUpdtDtm) {
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public AppCasePlanSpecificFields(AppCase appCase, Integer planSpecFieldId, String planSpecFieldValue,
			char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
		this.appCase = appCase;
		this.planSpecFieldId = planSpecFieldId;
		this.planSpecFieldValue = planSpecFieldValue;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_case_plan_specific_field_id", unique = true, nullable = false)
	public Integer getAppCasePlanSpecificFieldId() {
		return this.appCasePlanSpecificFieldId;
	}

	public void setAppCasePlanSpecificFieldId(Integer appCasePlanSpecificFieldId) {
		this.appCasePlanSpecificFieldId = appCasePlanSpecificFieldId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id")
	public AppCase getAppCase() {
		return this.appCase;
	}

	public void setAppCase(AppCase appCase) {
		this.appCase = appCase;
	}

	@Column(name = "plan_spec_field_id")
	public Integer getPlanSpecFieldId() {
		return this.planSpecFieldId;
	}

	public void setPlanSpecFieldId(Integer planSpecFieldId) {
		this.planSpecFieldId = planSpecFieldId;
	}

	@Column(name = "plan_spec_field_value", length = 20)
	public String getPlanSpecFieldValue() {
		return this.planSpecFieldValue;
	}

	public void setPlanSpecFieldValue(String planSpecFieldValue) {
		this.planSpecFieldValue = planSpecFieldValue;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
