package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * AppCase generated by hbm2java
 */
@Entity
@Table(name = "app_case")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AppCase implements java.io.Serializable {

	private Integer caseId;
	private Integer companyId;
	private String prodCd;
	private long tenantId;
	private String stateCd;
	private Date applicationSignDate;
	private String caseTypeCd;
	private Character saveAgeInd;
	private String productTypeCd;
	private Integer planId;
	private Integer planRateClassId;
	private String applnCaseTypeCd;
	private Date appReceivedDate;
	private String caseStatus;
	private Character cwaIndicator;
	private BigDecimal faceAmount;
	private BigDecimal amountCollected;
	private Character esignIndicator;
	private String clientFileNumber;
	private String policyControlNumber;
	private String businessCaseId;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private String illustrationHash;
	private String isIllustrationHashRequired;
	private Character isClonedCase;
	private String applicationEffDate;
	private Character isClonedForRi;
	private Integer clonedCaseFrom;
	private String iaScore;
	private String iaStatus;
	private Character isLdpCmpltd;
	private BigDecimal amtPymtEntry;
	private Set<CaseAgent> caseAgents = new HashSet<CaseAgent>(0);
	private Set<CaseViewStatus> caseViewStatuses = new HashSet<CaseViewStatus>(0);
	private Set<Benefit> benefits = new HashSet<Benefit>(0);
	private Set<CaseClientMap> caseClientMaps = new HashSet<CaseClientMap>(0);
	private Set<CasePremiumMode> casePremiumModes = new HashSet<CasePremiumMode>(0);
	private Set<CaseEsign> caseEsigns = new HashSet<CaseEsign>(0);
	private Set<CaseEsign> caseEsigns_1 = new HashSet<CaseEsign>(0);
	private Set<CaseEsign> caseEsigns_2 = new HashSet<CaseEsign>(0);
	private Set<CaseCoverage> caseCoverages = new HashSet<CaseCoverage>(0);
	private Set<AppCaseExchange> appCaseExchanges = new HashSet<AppCaseExchange>(0);
	private Set<AppCasePlanSpecificFields> appCasePlanSpecificFieldses = new HashSet<AppCasePlanSpecificFields>(0);
	private Set<CaseEsign> caseEsigns_3 = new HashSet<CaseEsign>(0);
	private Set<Rider> riders = new HashSet<Rider>(0);
	private Set<QuestionnaireAssociateInfo> questionnaireAssociateInfos = new HashSet<QuestionnaireAssociateInfo>(0);
	private Set<CaseEsign> caseEsigns_4 = new HashSet<CaseEsign>(0);
	private Set<CaseQuestionResourceMap> caseQuestionResourceMaps = new HashSet<CaseQuestionResourceMap>(0);
	private Set<CaseAltPremiumMode> caseAltPremiumModes = new HashSet<CaseAltPremiumMode>(0);

	public AppCase() {
	}

	public AppCase(long tenantId, char isDeletedInd, Date lstUpdtDtm) {
		this.tenantId = tenantId;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public AppCase(Integer companyId, String prodCd, long tenantId, String stateCd, Date applicationSignDate,
			String caseTypeCd, Character saveAgeInd, String productTypeCd, Integer planId, Integer planRateClassId,
			String applnCaseTypeCd, Date appReceivedDate, String caseStatus, Character cwaIndicator,
			BigDecimal faceAmount, BigDecimal amountCollected, Character esignIndicator, String clientFileNumber,
			String policyControlNumber, String businessCaseId, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm,
			String illustrationHash, String isIllustrationHashRequired, Character isClonedCase,
			String applicationEffDate, Character isClonedForRi, Integer clonedCaseFrom, String iaScore, String iaStatus,
			Character isLdpCmpltd, BigDecimal amtPymtEntry, Set<CaseAgent> caseAgents,
			Set<CaseViewStatus> caseViewStatuses, Set<Benefit> benefits, Set<CaseClientMap> caseClientMaps,
			Set<CasePremiumMode> casePremiumModes, Set<CaseEsign> caseEsigns, Set<CaseEsign> caseEsigns_1,
			Set<CaseEsign> caseEsigns_2, Set<CaseCoverage> caseCoverages, Set<AppCaseExchange> appCaseExchanges,
			Set<AppCasePlanSpecificFields> appCasePlanSpecificFieldses, Set<CaseEsign> caseEsigns_3, Set<Rider> riders,
			Set<QuestionnaireAssociateInfo> questionnaireAssociateInfos, Set<CaseEsign> caseEsigns_4,
			Set<CaseQuestionResourceMap> caseQuestionResourceMaps, Set<CaseAltPremiumMode> caseAltPremiumModes) {
		this.companyId = companyId;
		this.prodCd = prodCd;
		this.tenantId = tenantId;
		this.stateCd = stateCd;
		this.applicationSignDate = applicationSignDate;
		this.caseTypeCd = caseTypeCd;
		this.saveAgeInd = saveAgeInd;
		this.productTypeCd = productTypeCd;
		this.planId = planId;
		this.planRateClassId = planRateClassId;
		this.applnCaseTypeCd = applnCaseTypeCd;
		this.appReceivedDate = appReceivedDate;
		this.caseStatus = caseStatus;
		this.cwaIndicator = cwaIndicator;
		this.faceAmount = faceAmount;
		this.amountCollected = amountCollected;
		this.esignIndicator = esignIndicator;
		this.clientFileNumber = clientFileNumber;
		this.policyControlNumber = policyControlNumber;
		this.businessCaseId = businessCaseId;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.illustrationHash = illustrationHash;
		this.isIllustrationHashRequired = isIllustrationHashRequired;
		this.isClonedCase = isClonedCase;
		this.applicationEffDate = applicationEffDate;
		this.isClonedForRi = isClonedForRi;
		this.clonedCaseFrom = clonedCaseFrom;
		this.iaScore = iaScore;
		this.iaStatus = iaStatus;
		this.isLdpCmpltd = isLdpCmpltd;
		this.amtPymtEntry = amtPymtEntry;
		this.caseAgents = caseAgents;
		this.caseViewStatuses = caseViewStatuses;
		this.benefits = benefits;
		this.caseClientMaps = caseClientMaps;
		this.casePremiumModes = casePremiumModes;
		this.caseEsigns = caseEsigns;
		this.caseEsigns_1 = caseEsigns_1;
		this.caseEsigns_2 = caseEsigns_2;
		this.caseCoverages = caseCoverages;
		this.appCaseExchanges = appCaseExchanges;
		this.appCasePlanSpecificFieldses = appCasePlanSpecificFieldses;
		this.caseEsigns_3 = caseEsigns_3;
		this.riders = riders;
		this.questionnaireAssociateInfos = questionnaireAssociateInfos;
		this.caseEsigns_4 = caseEsigns_4;
		this.caseQuestionResourceMaps = caseQuestionResourceMaps;
		this.caseAltPremiumModes = caseAltPremiumModes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "case_id", unique = true, nullable = false)
	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "prod_cd", length = 10)
	public String getProdCd() {
		return this.prodCd;
	}

	public void setProdCd(String prodCd) {
		this.prodCd = prodCd;
	}

	@Column(name = "tenant_id", nullable = false)
	public long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(long tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "state_cd", length = 2)
	public String getStateCd() {
		return this.stateCd;
	}

	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "application_sign_date", length = 23)
	public Date getApplicationSignDate() {
		return this.applicationSignDate;
	}

	public void setApplicationSignDate(Date applicationSignDate) {
		this.applicationSignDate = applicationSignDate;
	}

	@Column(name = "case_type_cd", length = 20)
	public String getCaseTypeCd() {
		return this.caseTypeCd;
	}

	public void setCaseTypeCd(String caseTypeCd) {
		this.caseTypeCd = caseTypeCd;
	}

	@Column(name = "save_age_ind", length = 1)
	public Character getSaveAgeInd() {
		return this.saveAgeInd;
	}

	public void setSaveAgeInd(Character saveAgeInd) {
		this.saveAgeInd = saveAgeInd;
	}

	@Column(name = "product_type_cd", length = 50)
	public String getProductTypeCd() {
		return this.productTypeCd;
	}

	public void setProductTypeCd(String productTypeCd) {
		this.productTypeCd = productTypeCd;
	}

	@Column(name = "plan_id")
	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	@Column(name = "plan_rate_class_id")
	public Integer getPlanRateClassId() {
		return this.planRateClassId;
	}

	public void setPlanRateClassId(Integer planRateClassId) {
		this.planRateClassId = planRateClassId;
	}

	@Column(name = "appln_case_type_cd", length = 20)
	public String getApplnCaseTypeCd() {
		return this.applnCaseTypeCd;
	}

	public void setApplnCaseTypeCd(String applnCaseTypeCd) {
		this.applnCaseTypeCd = applnCaseTypeCd;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "app_received_date", length = 23)
	public Date getAppReceivedDate() {
		return this.appReceivedDate;
	}

	public void setAppReceivedDate(Date appReceivedDate) {
		this.appReceivedDate = appReceivedDate;
	}

	@Column(name = "case_status", length = 20)
	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	@Column(name = "cwa_indicator", length = 1)
	public Character getCwaIndicator() {
		return this.cwaIndicator;
	}

	public void setCwaIndicator(Character cwaIndicator) {
		this.cwaIndicator = cwaIndicator;
	}

	@Column(name = "face_amount", precision = 12)
	public BigDecimal getFaceAmount() {
		return this.faceAmount;
	}

	public void setFaceAmount(BigDecimal faceAmount) {
		this.faceAmount = faceAmount;
	}

	@Column(name = "amount_collected", precision = 12)
	public BigDecimal getAmountCollected() {
		return this.amountCollected;
	}

	public void setAmountCollected(BigDecimal amountCollected) {
		this.amountCollected = amountCollected;
	}

	@Column(name = "esign_indicator", length = 1)
	public Character getEsignIndicator() {
		return this.esignIndicator;
	}

	public void setEsignIndicator(Character esignIndicator) {
		this.esignIndicator = esignIndicator;
	}

	@Column(name = "client_file_number", length = 50)
	public String getClientFileNumber() {
		return this.clientFileNumber;
	}

	public void setClientFileNumber(String clientFileNumber) {
		this.clientFileNumber = clientFileNumber;
	}

	@Column(name = "policy_control_number", length = 50)
	public String getPolicyControlNumber() {
		return this.policyControlNumber;
	}

	public void setPolicyControlNumber(String policyControlNumber) {
		this.policyControlNumber = policyControlNumber;
	}

	@Column(name = "business_case_id", length = 10)
	public String getBusinessCaseId() {
		return this.businessCaseId;
	}

	public void setBusinessCaseId(String businessCaseId) {
		this.businessCaseId = businessCaseId;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "illustration_hash", length = 50)
	public String getIllustrationHash() {
		return this.illustrationHash;
	}

	public void setIllustrationHash(String illustrationHash) {
		this.illustrationHash = illustrationHash;
	}

	@Column(name = "is_illustration_hash_required", length = 20)
	public String getIsIllustrationHashRequired() {
		return this.isIllustrationHashRequired;
	}

	public void setIsIllustrationHashRequired(String isIllustrationHashRequired) {
		this.isIllustrationHashRequired = isIllustrationHashRequired;
	}

	@Column(name = "is_cloned_case", length = 1)
	public Character getIsClonedCase() {
		return this.isClonedCase;
	}

	public void setIsClonedCase(Character isClonedCase) {
		this.isClonedCase = isClonedCase;
	}

	@Column(name = "application_eff_date", length = 20)
	public String getApplicationEffDate() {
		return this.applicationEffDate;
	}

	public void setApplicationEffDate(String applicationEffDate) {
		this.applicationEffDate = applicationEffDate;
	}

	@Column(name = "is_cloned_for_ri", length = 1)
	public Character getIsClonedForRi() {
		return this.isClonedForRi;
	}

	public void setIsClonedForRi(Character isClonedForRi) {
		this.isClonedForRi = isClonedForRi;
	}

	@Column(name = "cloned_case_from")
	public Integer getClonedCaseFrom() {
		return this.clonedCaseFrom;
	}

	public void setClonedCaseFrom(Integer clonedCaseFrom) {
		this.clonedCaseFrom = clonedCaseFrom;
	}

	@Column(name = "ia_score", length = 15)
	public String getIaScore() {
		return this.iaScore;
	}

	public void setIaScore(String iaScore) {
		this.iaScore = iaScore;
	}

	@Column(name = "ia_status", length = 100)
	public String getIaStatus() {
		return this.iaStatus;
	}

	public void setIaStatus(String iaStatus) {
		this.iaStatus = iaStatus;
	}

	@Column(name = "is_ldp_cmpltd", length = 1)
	public Character getIsLdpCmpltd() {
		return this.isLdpCmpltd;
	}

	public void setIsLdpCmpltd(Character isLdpCmpltd) {
		this.isLdpCmpltd = isLdpCmpltd;
	}

	@Column(name = "amt_pymt_entry", precision = 12)
	public BigDecimal getAmtPymtEntry() {
		return this.amtPymtEntry;
	}

	public void setAmtPymtEntry(BigDecimal amtPymtEntry) {
		this.amtPymtEntry = amtPymtEntry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseAgent> getCaseAgents() {
		return this.caseAgents;
	}

	public void setCaseAgents(Set<CaseAgent> caseAgents) {
		this.caseAgents = caseAgents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseViewStatus> getCaseViewStatuses() {
		return this.caseViewStatuses;
	}

	public void setCaseViewStatuses(Set<CaseViewStatus> caseViewStatuses) {
		this.caseViewStatuses = caseViewStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<Benefit> getBenefits() {
		return this.benefits;
	}

	public void setBenefits(Set<Benefit> benefits) {
		this.benefits = benefits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseClientMap> getCaseClientMaps() {
		return this.caseClientMaps;
	}

	public void setCaseClientMaps(Set<CaseClientMap> caseClientMaps) {
		this.caseClientMaps = caseClientMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CasePremiumMode> getCasePremiumModes() {
		return this.casePremiumModes;
	}

	public void setCasePremiumModes(Set<CasePremiumMode> casePremiumModes) {
		this.casePremiumModes = casePremiumModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseEsign> getCaseEsigns() {
		return this.caseEsigns;
	}

	public void setCaseEsigns(Set<CaseEsign> caseEsigns) {
		this.caseEsigns = caseEsigns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseEsign> getCaseEsigns_1() {
		return this.caseEsigns_1;
	}

	public void setCaseEsigns_1(Set<CaseEsign> caseEsigns_1) {
		this.caseEsigns_1 = caseEsigns_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseEsign> getCaseEsigns_2() {
		return this.caseEsigns_2;
	}

	public void setCaseEsigns_2(Set<CaseEsign> caseEsigns_2) {
		this.caseEsigns_2 = caseEsigns_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseCoverage> getCaseCoverages() {
		return this.caseCoverages;
	}

	public void setCaseCoverages(Set<CaseCoverage> caseCoverages) {
		this.caseCoverages = caseCoverages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<AppCaseExchange> getAppCaseExchanges() {
		return this.appCaseExchanges;
	}

	public void setAppCaseExchanges(Set<AppCaseExchange> appCaseExchanges) {
		this.appCaseExchanges = appCaseExchanges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<AppCasePlanSpecificFields> getAppCasePlanSpecificFieldses() {
		return this.appCasePlanSpecificFieldses;
	}

	public void setAppCasePlanSpecificFieldses(Set<AppCasePlanSpecificFields> appCasePlanSpecificFieldses) {
		this.appCasePlanSpecificFieldses = appCasePlanSpecificFieldses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseEsign> getCaseEsigns_3() {
		return this.caseEsigns_3;
	}

	public void setCaseEsigns_3(Set<CaseEsign> caseEsigns_3) {
		this.caseEsigns_3 = caseEsigns_3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<Rider> getRiders() {
		return this.riders;
	}

	public void setRiders(Set<Rider> riders) {
		this.riders = riders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<QuestionnaireAssociateInfo> getQuestionnaireAssociateInfos() {
		return this.questionnaireAssociateInfos;
	}

	public void setQuestionnaireAssociateInfos(Set<QuestionnaireAssociateInfo> questionnaireAssociateInfos) {
		this.questionnaireAssociateInfos = questionnaireAssociateInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseEsign> getCaseEsigns_4() {
		return this.caseEsigns_4;
	}

	public void setCaseEsigns_4(Set<CaseEsign> caseEsigns_4) {
		this.caseEsigns_4 = caseEsigns_4;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseQuestionResourceMap> getCaseQuestionResourceMaps() {
		return this.caseQuestionResourceMaps;
	}

	public void setCaseQuestionResourceMaps(Set<CaseQuestionResourceMap> caseQuestionResourceMaps) {
		this.caseQuestionResourceMaps = caseQuestionResourceMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appCase")
	public Set<CaseAltPremiumMode> getCaseAltPremiumModes() {
		return this.caseAltPremiumModes;
	}

	public void setCaseAltPremiumModes(Set<CaseAltPremiumMode> caseAltPremiumModes) {
		this.caseAltPremiumModes = caseAltPremiumModes;
	}

}
