package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * BaseProductsLimits generated by hbm2java
 */
@Entity
@Table(name = "base_products_limits")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BaseProductsLimits implements java.io.Serializable {

	private int id;
	private Short minAge;
	private Short maxAge;
	private Double minFaceAmt;
	private Double maxFaceAmt;

	public BaseProductsLimits() {
	}

	public BaseProductsLimits(int id) {
		this.id = id;
	}

	public BaseProductsLimits(int id, Short minAge, Short maxAge, Double minFaceAmt, Double maxFaceAmt) {
		this.id = id;
		this.minAge = minAge;
		this.maxAge = maxAge;
		this.minFaceAmt = minFaceAmt;
		this.maxFaceAmt = maxFaceAmt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "min_age")
	public Short getMinAge() {
		return this.minAge;
	}

	public void setMinAge(Short minAge) {
		this.minAge = minAge;
	}

	@Column(name = "max_age")
	public Short getMaxAge() {
		return this.maxAge;
	}

	public void setMaxAge(Short maxAge) {
		this.maxAge = maxAge;
	}

	@Column(name = "min_face_amt", precision = 53, scale = 0)
	public Double getMinFaceAmt() {
		return this.minFaceAmt;
	}

	public void setMinFaceAmt(Double minFaceAmt) {
		this.minFaceAmt = minFaceAmt;
	}

	@Column(name = "max_face_amt", precision = 53, scale = 0)
	public Double getMaxFaceAmt() {
		return this.maxFaceAmt;
	}

	public void setMaxFaceAmt(Double maxFaceAmt) {
		this.maxFaceAmt = maxFaceAmt;
	}

}
