package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * BaseProducts generated by hbm2java
 */
@Entity
@Table(name = "base_products")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BaseProducts implements java.io.Serializable {

	private int prodId;
	private String prodCd;
	private String prodNm;
	private String prodTypCd;
	private String lifeTypCd;
	private Integer companyId;
	private Character isActive;
	private Character isPublished;
	private Character isDeletedInd;
	private Date lstUpdtDtm;
	private String lstUpdtUserId;

	public BaseProducts() {
	}

	public BaseProducts(int prodId) {
		this.prodId = prodId;
	}

	public BaseProducts(int prodId, String prodCd, String prodNm, String prodTypCd, String lifeTypCd, Integer companyId,
			Character isActive, Character isPublished, Character isDeletedInd, Date lstUpdtDtm, String lstUpdtUserId) {
		this.prodId = prodId;
		this.prodCd = prodCd;
		this.prodNm = prodNm;
		this.prodTypCd = prodTypCd;
		this.lifeTypCd = lifeTypCd;
		this.companyId = companyId;
		this.isActive = isActive;
		this.isPublished = isPublished;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@Id

	@Column(name = "prod_id", unique = true, nullable = false)
	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	@Column(name = "prod_cd", length = 12)
	public String getProdCd() {
		return this.prodCd;
	}

	public void setProdCd(String prodCd) {
		this.prodCd = prodCd;
	}

	@Column(name = "prod_nm", length = 100)
	public String getProdNm() {
		return this.prodNm;
	}

	public void setProdNm(String prodNm) {
		this.prodNm = prodNm;
	}

	@Column(name = "prod_typ_cd", length = 8)
	public String getProdTypCd() {
		return this.prodTypCd;
	}

	public void setProdTypCd(String prodTypCd) {
		this.prodTypCd = prodTypCd;
	}

	@Column(name = "life_typ_cd", length = 8)
	public String getLifeTypCd() {
		return this.lifeTypCd;
	}

	public void setLifeTypCd(String lifeTypCd) {
		this.lifeTypCd = lifeTypCd;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "is_active", length = 1)
	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	@Column(name = "is_published", length = 1)
	public Character getIsPublished() {
		return this.isPublished;
	}

	public void setIsPublished(Character isPublished) {
		this.isPublished = isPublished;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

}
