package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * BeneTyp generated by hbm2java
 */
@Entity
@Table(name = "bene_typ")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BeneTyp implements java.io.Serializable {

	private String beneTypCd;
	private String beneTypNm;
	private Short beneSortNum;
	private Character isDeletedInd;
	private String lstUpdtUserid;
	private Date lstUpdtDtm;

	public BeneTyp() {
	}

	public BeneTyp(String beneTypCd) {
		this.beneTypCd = beneTypCd;
	}

	public BeneTyp(String beneTypCd, String beneTypNm, Short beneSortNum, Character isDeletedInd, String lstUpdtUserid,
			Date lstUpdtDtm) {
		this.beneTypCd = beneTypCd;
		this.beneTypNm = beneTypNm;
		this.beneSortNum = beneSortNum;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserid = lstUpdtUserid;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "bene_typ_cd", unique = true, nullable = false, length = 8)
	public String getBeneTypCd() {
		return this.beneTypCd;
	}

	public void setBeneTypCd(String beneTypCd) {
		this.beneTypCd = beneTypCd;
	}

	@Column(name = "bene_typ_nm", length = 20)
	public String getBeneTypNm() {
		return this.beneTypNm;
	}

	public void setBeneTypNm(String beneTypNm) {
		this.beneTypNm = beneTypNm;
	}

	@Column(name = "bene_sort_num")
	public Short getBeneSortNum() {
		return this.beneSortNum;
	}

	public void setBeneSortNum(Short beneSortNum) {
		this.beneSortNum = beneSortNum;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_userid", length = 20)
	public String getLstUpdtUserid() {
		return this.lstUpdtUserid;
	}

	public void setLstUpdtUserid(String lstUpdtUserid) {
		this.lstUpdtUserid = lstUpdtUserid;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
