package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillingFormType generated by hbm2java
 */
@Entity
@Table(name="billing_form_type"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class BillingFormType  implements java.io.Serializable {


     private String billFormTypCd;
     private String billFormTypDesc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public BillingFormType() {
    }

	
    public BillingFormType(String billFormTypCd, char isDeletedInd, Date lstUpdtDtm) {
        this.billFormTypCd = billFormTypCd;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public BillingFormType(String billFormTypCd, String billFormTypDesc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.billFormTypCd = billFormTypCd;
       this.billFormTypDesc = billFormTypDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="bill_form_typ_cd", unique=true, nullable=false, length=20)
    public String getBillFormTypCd() {
        return this.billFormTypCd;
    }
    
    public void setBillFormTypCd(String billFormTypCd) {
        this.billFormTypCd = billFormTypCd;
    }

    
    @Column(name="bill_form_typ_desc", length=50)
    public String getBillFormTypDesc() {
        return this.billFormTypDesc;
    }
    
    public void setBillFormTypDesc(String billFormTypDesc) {
        this.billFormTypDesc = billFormTypDesc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


