package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * BusinessMode generated by hbm2java
 */
@Entity
@Table(name = "business_mode")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BusinessMode implements java.io.Serializable {

	private String businessModeCd;
	private String businessModeDesc;
	private Character isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public BusinessMode() {
	}

	public BusinessMode(String businessModeCd, String businessModeDesc) {
		this.businessModeCd = businessModeCd;
		this.businessModeDesc = businessModeDesc;
	}

	public BusinessMode(String businessModeCd, String businessModeDesc, Character isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm) {
		this.businessModeCd = businessModeCd;
		this.businessModeDesc = businessModeDesc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "business_mode_cd", unique = true, nullable = false, length = 20)
	public String getBusinessModeCd() {
		return this.businessModeCd;
	}

	public void setBusinessModeCd(String businessModeCd) {
		this.businessModeCd = businessModeCd;
	}

	@Column(name = "business_mode_desc", nullable = false, length = 50)
	public String getBusinessModeDesc() {
		return this.businessModeDesc;
	}

	public void setBusinessModeDesc(String businessModeDesc) {
		this.businessModeDesc = businessModeDesc;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
