package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * CaseClientEmploymentDetails generated by hbm2java
 */
@Entity
@Table(name = "case_client_employment_details")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class CaseClientEmploymentDetails implements java.io.Serializable {

	private Integer caseClientEmploymentDetailsId;
	private CaseClientMap caseClientMap;
	private Character employeeInd;
	private String employerNm;
	private String occupationCd;
	private String experienceWithCurrentEmployer;
	private String hoursWorkedPerWeek;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private String otherOccupation;

	public CaseClientEmploymentDetails() {
	}

	public CaseClientEmploymentDetails(char isDeletedInd, Date lstUpdtDtm) {
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public CaseClientEmploymentDetails(CaseClientMap caseClientMap, Character employeeInd, String employerNm,
			String occupationCd, String experienceWithCurrentEmployer, String hoursWorkedPerWeek, char isDeletedInd,
			String lstUpdtUserId, Date lstUpdtDtm, String otherOccupation) {
		this.caseClientMap = caseClientMap;
		this.employeeInd = employeeInd;
		this.employerNm = employerNm;
		this.occupationCd = occupationCd;
		this.experienceWithCurrentEmployer = experienceWithCurrentEmployer;
		this.hoursWorkedPerWeek = hoursWorkedPerWeek;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.otherOccupation = otherOccupation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "case_client_employment_details_id", unique = true, nullable = false)
	public Integer getCaseClientEmploymentDetailsId() {
		return this.caseClientEmploymentDetailsId;
	}

	public void setCaseClientEmploymentDetailsId(Integer caseClientEmploymentDetailsId) {
		this.caseClientEmploymentDetailsId = caseClientEmploymentDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_client_map_id")
	public CaseClientMap getCaseClientMap() {
		return this.caseClientMap;
	}

	public void setCaseClientMap(CaseClientMap caseClientMap) {
		this.caseClientMap = caseClientMap;
	}

	@Column(name = "employee_ind", length = 1)
	public Character getEmployeeInd() {
		return this.employeeInd;
	}

	public void setEmployeeInd(Character employeeInd) {
		this.employeeInd = employeeInd;
	}

	@Column(name = "employer_nm", length = 100)
	public String getEmployerNm() {
		return this.employerNm;
	}

	public void setEmployerNm(String employerNm) {
		this.employerNm = employerNm;
	}

	@Column(name = "occupation_cd", length = 20)
	public String getOccupationCd() {
		return this.occupationCd;
	}

	public void setOccupationCd(String occupationCd) {
		this.occupationCd = occupationCd;
	}

	@Column(name = "experience_with_current_employer", length = 32)
	public String getExperienceWithCurrentEmployer() {
		return this.experienceWithCurrentEmployer;
	}

	public void setExperienceWithCurrentEmployer(String experienceWithCurrentEmployer) {
		this.experienceWithCurrentEmployer = experienceWithCurrentEmployer;
	}

	@Column(name = "hours_worked_per_week", length = 32)
	public String getHoursWorkedPerWeek() {
		return this.hoursWorkedPerWeek;
	}

	public void setHoursWorkedPerWeek(String hoursWorkedPerWeek) {
		this.hoursWorkedPerWeek = hoursWorkedPerWeek;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "other_occupation")
	public String getOtherOccupation() {
		return this.otherOccupation;
	}

	public void setOtherOccupation(String otherOccupation) {
		this.otherOccupation = otherOccupation;
	}

}
