package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * CaseClientReplacingInforcePolicyDetails generated by hbm2java
 */
@Entity
@Table(name = "case_client_replacing_inforce_policy_details")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class CaseClientReplacingInforcePolicyDetails implements java.io.Serializable {

	private Integer caseClientReplacingInforcePolicyDetailsId;
	private CaseClientMap caseClientMap;
	private Integer companyId;
	private String existingCompanyNm;
	private String policyType;
	private BigDecimal faceAmount;
	private String policyEffectiveDate;
	private String policyNumber;
	private String benefitOrRiderNames;
	private String is1035ReplaceInd;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public CaseClientReplacingInforcePolicyDetails() {
	}

	public CaseClientReplacingInforcePolicyDetails(char isDeletedInd, Date lstUpdtDtm) {
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public CaseClientReplacingInforcePolicyDetails(CaseClientMap caseClientMap, Integer companyId,
			String existingCompanyNm, String policyType, BigDecimal faceAmount, String policyEffectiveDate,
			String policyNumber, String benefitOrRiderNames, String is1035ReplaceInd, char isDeletedInd,
			String lstUpdtUserId, Date lstUpdtDtm) {
		this.caseClientMap = caseClientMap;
		this.companyId = companyId;
		this.existingCompanyNm = existingCompanyNm;
		this.policyType = policyType;
		this.faceAmount = faceAmount;
		this.policyEffectiveDate = policyEffectiveDate;
		this.policyNumber = policyNumber;
		this.benefitOrRiderNames = benefitOrRiderNames;
		this.is1035ReplaceInd = is1035ReplaceInd;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "case_client_replacing_inforce_policy_details_id", unique = true, nullable = false)
	public Integer getCaseClientReplacingInforcePolicyDetailsId() {
		return this.caseClientReplacingInforcePolicyDetailsId;
	}

	public void setCaseClientReplacingInforcePolicyDetailsId(Integer caseClientReplacingInforcePolicyDetailsId) {
		this.caseClientReplacingInforcePolicyDetailsId = caseClientReplacingInforcePolicyDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_client_map_id")
	public CaseClientMap getCaseClientMap() {
		return this.caseClientMap;
	}

	public void setCaseClientMap(CaseClientMap caseClientMap) {
		this.caseClientMap = caseClientMap;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "existing_company_nm", length = 50)
	public String getExistingCompanyNm() {
		return this.existingCompanyNm;
	}

	public void setExistingCompanyNm(String existingCompanyNm) {
		this.existingCompanyNm = existingCompanyNm;
	}

	@Column(name = "policy_type", length = 50)
	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	@Column(name = "face_amount", precision = 15)
	public BigDecimal getFaceAmount() {
		return this.faceAmount;
	}

	public void setFaceAmount(BigDecimal faceAmount) {
		this.faceAmount = faceAmount;
	}

	@Column(name = "policy_effective_date", length = 50)
	public String getPolicyEffectiveDate() {
		return this.policyEffectiveDate;
	}

	public void setPolicyEffectiveDate(String policyEffectiveDate) {
		this.policyEffectiveDate = policyEffectiveDate;
	}

	@Column(name = "policy_number", length = 25)
	public String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	@Column(name = "benefit_or_rider_names", length = 50)
	public String getBenefitOrRiderNames() {
		return this.benefitOrRiderNames;
	}

	public void setBenefitOrRiderNames(String benefitOrRiderNames) {
		this.benefitOrRiderNames = benefitOrRiderNames;
	}

	@Column(name = "is_1035_replace_ind", length = 5)
	public String getIs1035ReplaceInd() {
		return this.is1035ReplaceInd;
	}

	public void setIs1035ReplaceInd(String is1035ReplaceInd) {
		this.is1035ReplaceInd = is1035ReplaceInd;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
