package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaseClientEstatePlanning generated by hbm2java
 */
@Entity
@Table(name="case_client_estate_planning"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class CaseClientEstatePlanning  implements java.io.Serializable {


     private Integer caseClientEstatePlanningId;
     private CaseClientMap caseClientMap;
     private String estateTypeCd;
     private String estateTypeOther;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public CaseClientEstatePlanning() {
    }

	
    public CaseClientEstatePlanning(char isDeletedInd, Date lstUpdtDtm) {
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public CaseClientEstatePlanning(CaseClientMap caseClientMap, String estateTypeCd, String estateTypeOther, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.caseClientMap = caseClientMap;
       this.estateTypeCd = estateTypeCd;
       this.estateTypeOther = estateTypeOther;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="case_client_estate_planning_id", unique=true, nullable=false)
    public Integer getCaseClientEstatePlanningId() {
        return this.caseClientEstatePlanningId;
    }
    
    public void setCaseClientEstatePlanningId(Integer caseClientEstatePlanningId) {
        this.caseClientEstatePlanningId = caseClientEstatePlanningId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_client_map_id")
    public CaseClientMap getCaseClientMap() {
        return this.caseClientMap;
    }
    
    public void setCaseClientMap(CaseClientMap caseClientMap) {
        this.caseClientMap = caseClientMap;
    }

    
    @Column(name="estate_type_cd", length=20)
    public String getEstateTypeCd() {
        return this.estateTypeCd;
    }
    
    public void setEstateTypeCd(String estateTypeCd) {
        this.estateTypeCd = estateTypeCd;
    }

    
    @Column(name="estate_type_other", length=50)
    public String getEstateTypeOther() {
        return this.estateTypeOther;
    }
    
    public void setEstateTypeOther(String estateTypeOther) {
        this.estateTypeOther = estateTypeOther;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


