package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaseAltPremiumMode generated by hbm2java
 */
@Entity
@Table(name="case_alt_premium_mode"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class CaseAltPremiumMode  implements java.io.Serializable {


     private BigDecimal caseAltPremiumModeId;
     private AppCase appCase;
     private Integer paymentModeTc;
     private String paymentMode;
     private Integer paymentMethodTc;
     private String paymentMethod;
     private Double paymentAmount;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public CaseAltPremiumMode() {
    }

	
    public CaseAltPremiumMode(AppCase appCase, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
        this.appCase = appCase;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtUserId = lstUpdtUserId;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public CaseAltPremiumMode(AppCase appCase, Integer paymentModeTc, String paymentMode, Integer paymentMethodTc, String paymentMethod, Double paymentAmount, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.appCase = appCase;
       this.paymentModeTc = paymentModeTc;
       this.paymentMode = paymentMode;
       this.paymentMethodTc = paymentMethodTc;
       this.paymentMethod = paymentMethod;
       this.paymentAmount = paymentAmount;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="case_alt_premium_mode_id", unique=true, nullable=false, scale=0)
    public BigDecimal getCaseAltPremiumModeId() {
        return this.caseAltPremiumModeId;
    }
    
    public void setCaseAltPremiumModeId(BigDecimal caseAltPremiumModeId) {
        this.caseAltPremiumModeId = caseAltPremiumModeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_id", nullable=false)
    public AppCase getAppCase() {
        return this.appCase;
    }
    
    public void setAppCase(AppCase appCase) {
        this.appCase = appCase;
    }

    
    @Column(name="payment_mode_tc")
    public Integer getPaymentModeTc() {
        return this.paymentModeTc;
    }
    
    public void setPaymentModeTc(Integer paymentModeTc) {
        this.paymentModeTc = paymentModeTc;
    }

    
    @Column(name="payment_mode")
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    
    @Column(name="payment_method_tc")
    public Integer getPaymentMethodTc() {
        return this.paymentMethodTc;
    }
    
    public void setPaymentMethodTc(Integer paymentMethodTc) {
        this.paymentMethodTc = paymentMethodTc;
    }

    
    @Column(name="payment_method")
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="payment_amount", precision=53, scale=0)
    public Double getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(Double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", nullable=false, length=20)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


