package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * CaseClientQuestionResponse generated by hbm2java
 */
@Entity
@Table(name = "case_client_question_response")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class CaseClientQuestionResponse implements java.io.Serializable {

	private CaseClientQuestionResponseId id;
	private CaseClientMap caseClientMap;
	private int questionnaireId;
	private Integer responseIndex;
	private String responseValue;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private String questionDesc;

	public CaseClientQuestionResponse() {
	}

	public CaseClientQuestionResponse(CaseClientQuestionResponseId id, CaseClientMap caseClientMap, int questionnaireId,
			char isDeletedInd, Date lstUpdtDtm) {
		this.id = id;
		this.caseClientMap = caseClientMap;
		this.questionnaireId = questionnaireId;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public CaseClientQuestionResponse(CaseClientQuestionResponseId id, CaseClientMap caseClientMap, int questionnaireId,
			Integer responseIndex, String responseValue, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm,
			String questionDesc) {
		this.id = id;
		this.caseClientMap = caseClientMap;
		this.questionnaireId = questionnaireId;
		this.responseIndex = responseIndex;
		this.responseValue = responseValue;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.questionDesc = questionDesc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "caseClientMapId", column = @Column(name = "case_client_map_id", nullable = false)),
			@AttributeOverride(name = "questionId", column = @Column(name = "question_id", nullable = false)) })
	public CaseClientQuestionResponseId getId() {
		return this.id;
	}

	public void setId(CaseClientQuestionResponseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_client_map_id", nullable = false, insertable = false, updatable = false)
	public CaseClientMap getCaseClientMap() {
		return this.caseClientMap;
	}

	public void setCaseClientMap(CaseClientMap caseClientMap) {
		this.caseClientMap = caseClientMap;
	}

	@Column(name = "questionnaire_id", nullable = false)
	public int getQuestionnaireId() {
		return this.questionnaireId;
	}

	public void setQuestionnaireId(int questionnaireId) {
		this.questionnaireId = questionnaireId;
	}

	@Column(name = "response_index")
	public Integer getResponseIndex() {
		return this.responseIndex;
	}

	public void setResponseIndex(Integer responseIndex) {
		this.responseIndex = responseIndex;
	}

	@Column(name = "response_value", length = 50)
	public String getResponseValue() {
		return this.responseValue;
	}

	public void setResponseValue(String responseValue) {
		this.responseValue = responseValue;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "question_desc", length = 100)
	public String getQuestionDesc() {
		return this.questionDesc;
	}

	public void setQuestionDesc(String questionDesc) {
		this.questionDesc = questionDesc;
	}

}
