package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaseCoverageDetails generated by hbm2java
 */
@Entity
@Table(name="case_coverage_details"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class CaseCoverageDetails  implements java.io.Serializable {


     private Integer caseCoverageDetailsId;
     private CaseCoverage caseCoverage;
     private Integer benefitRiderSpecificAttribute;
     private String benefitRiderSpecificAttributeValue;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public CaseCoverageDetails() {
    }

	
    public CaseCoverageDetails(char isDeletedInd, Date lstUpdtDtm) {
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public CaseCoverageDetails(CaseCoverage caseCoverage, Integer benefitRiderSpecificAttribute, String benefitRiderSpecificAttributeValue, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.caseCoverage = caseCoverage;
       this.benefitRiderSpecificAttribute = benefitRiderSpecificAttribute;
       this.benefitRiderSpecificAttributeValue = benefitRiderSpecificAttributeValue;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="case_coverage_details_id", unique=true, nullable=false)
    public Integer getCaseCoverageDetailsId() {
        return this.caseCoverageDetailsId;
    }
    
    public void setCaseCoverageDetailsId(Integer caseCoverageDetailsId) {
        this.caseCoverageDetailsId = caseCoverageDetailsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_coverage_id")
    public CaseCoverage getCaseCoverage() {
        return this.caseCoverage;
    }
    
    public void setCaseCoverage(CaseCoverage caseCoverage) {
        this.caseCoverage = caseCoverage;
    }

    
    @Column(name="benefit_rider_specific_attribute")
    public Integer getBenefitRiderSpecificAttribute() {
        return this.benefitRiderSpecificAttribute;
    }
    
    public void setBenefitRiderSpecificAttribute(Integer benefitRiderSpecificAttribute) {
        this.benefitRiderSpecificAttribute = benefitRiderSpecificAttribute;
    }

    
    @Column(name="benefit_rider_specific_attribute_value", length=50)
    public String getBenefitRiderSpecificAttributeValue() {
        return this.benefitRiderSpecificAttributeValue;
    }
    
    public void setBenefitRiderSpecificAttributeValue(String benefitRiderSpecificAttributeValue) {
        this.benefitRiderSpecificAttributeValue = benefitRiderSpecificAttributeValue;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


