package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * CaseClientCoverage generated by hbm2java
 */
@Entity
@Table(name = "case_client_coverage")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class CaseClientCoverage implements java.io.Serializable {

	private Integer caseClientCoverageId;
	private CaseClientMap caseClientMap;
	private CaseCoverage caseCoverage;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public CaseClientCoverage() {
	}

	public CaseClientCoverage(char isDeletedInd, Date lstUpdtDtm) {
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public CaseClientCoverage(CaseClientMap caseClientMap, CaseCoverage caseCoverage, char isDeletedInd,
			String lstUpdtUserId, Date lstUpdtDtm) {
		this.caseClientMap = caseClientMap;
		this.caseCoverage = caseCoverage;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "case_client_coverage_id", unique = true, nullable = false)
	public Integer getCaseClientCoverageId() {
		return this.caseClientCoverageId;
	}

	public void setCaseClientCoverageId(Integer caseClientCoverageId) {
		this.caseClientCoverageId = caseClientCoverageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_client_map_id")
	public CaseClientMap getCaseClientMap() {
		return this.caseClientMap;
	}

	public void setCaseClientMap(CaseClientMap caseClientMap) {
		this.caseClientMap = caseClientMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_coverage_id")
	public CaseCoverage getCaseCoverage() {
		return this.caseCoverage;
	}

	public void setCaseCoverage(CaseCoverage caseCoverage) {
		this.caseCoverage = caseCoverage;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
