package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaseClientContactDetails generated by hbm2java
 */
@Entity
@Table(name="case_client_contact_details"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class CaseClientContactDetails  implements java.io.Serializable {


     private Integer caseClientContactDetailsId;
     private CaseClientMap caseClientMap;
     private String contactTypeCd;
     private String bestTimeToCall;
     private String bestPlaceToCall;
     private String phoneNumber;
     private String contactValue;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public CaseClientContactDetails() {
    }

	
    public CaseClientContactDetails(char isDeletedInd, Date lstUpdtDtm) {
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public CaseClientContactDetails(CaseClientMap caseClientMap, String contactTypeCd, String bestTimeToCall, String bestPlaceToCall, String phoneNumber, String contactValue, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.caseClientMap = caseClientMap;
       this.contactTypeCd = contactTypeCd;
       this.bestTimeToCall = bestTimeToCall;
       this.bestPlaceToCall = bestPlaceToCall;
       this.phoneNumber = phoneNumber;
       this.contactValue = contactValue;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="case_client_contact_details_id", unique=true, nullable=false)
    public Integer getCaseClientContactDetailsId() {
        return this.caseClientContactDetailsId;
    }
    
    public void setCaseClientContactDetailsId(Integer caseClientContactDetailsId) {
        this.caseClientContactDetailsId = caseClientContactDetailsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_client_map_id")
    public CaseClientMap getCaseClientMap() {
        return this.caseClientMap;
    }
    
    public void setCaseClientMap(CaseClientMap caseClientMap) {
        this.caseClientMap = caseClientMap;
    }

    
    @Column(name="contact_type_cd", length=20)
    public String getContactTypeCd() {
        return this.contactTypeCd;
    }
    
    public void setContactTypeCd(String contactTypeCd) {
        this.contactTypeCd = contactTypeCd;
    }

    
    @Column(name="best_time_to_call", length=8)
    public String getBestTimeToCall() {
        return this.bestTimeToCall;
    }
    
    public void setBestTimeToCall(String bestTimeToCall) {
        this.bestTimeToCall = bestTimeToCall;
    }

    
    @Column(name="best_place_to_call", length=8)
    public String getBestPlaceToCall() {
        return this.bestPlaceToCall;
    }
    
    public void setBestPlaceToCall(String bestPlaceToCall) {
        this.bestPlaceToCall = bestPlaceToCall;
    }

    
    @Column(name="phone_number", length=22)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="contact_value", length=100)
    public String getContactValue() {
        return this.contactValue;
    }
    
    public void setContactValue(String contactValue) {
        this.contactValue = contactValue;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


