package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CaseClientQuestionResponseId generated by hbm2java
 */
@Embeddable
public class CaseClientQuestionResponseId  implements java.io.Serializable {


     private int caseClientMapId;
     private int questionId;

    public CaseClientQuestionResponseId() {
    }

    public CaseClientQuestionResponseId(int caseClientMapId, int questionId) {
       this.caseClientMapId = caseClientMapId;
       this.questionId = questionId;
    }
   


    @Column(name="case_client_map_id", nullable=false)
    public int getCaseClientMapId() {
        return this.caseClientMapId;
    }
    
    public void setCaseClientMapId(int caseClientMapId) {
        this.caseClientMapId = caseClientMapId;
    }


    @Column(name="question_id", nullable=false)
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaseClientQuestionResponseId) ) return false;
		 CaseClientQuestionResponseId castOther = ( CaseClientQuestionResponseId ) other; 
         
		 return (this.getCaseClientMapId()==castOther.getCaseClientMapId())
 && (this.getQuestionId()==castOther.getQuestionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCaseClientMapId();
         result = 37 * result + this.getQuestionId();
         return result;
   }   


}


