package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaseEsign generated by hbm2java
 */
@Entity
@Table(name="case_esign"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class CaseEsign  implements java.io.Serializable {


     private Integer id;
     private AppCase appCase;
     private String esignId;
     private String esignStatusCd;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private String signedAt;
     private Character esignorwetsignInd;
     private Character isParentPresentTosign;

    public CaseEsign() {
    }

	
    public CaseEsign(char isDeletedInd, Date lstUpdtDtm) {
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public CaseEsign(AppCase appCase, String esignId, String esignStatusCd, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, String signedAt, Character esignorwetsignInd, Character isParentPresentTosign) {
       this.appCase = appCase;
       this.esignId = esignId;
       this.esignStatusCd = esignStatusCd;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.signedAt = signedAt;
       this.esignorwetsignInd = esignorwetsignInd;
       this.isParentPresentTosign = isParentPresentTosign;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CASE_ID")
    public AppCase getAppCase() {
        return this.appCase;
    }
    
    public void setAppCase(AppCase appCase) {
        this.appCase = appCase;
    }

    
    @Column(name="esign_id", length=20)
    public String getEsignId() {
        return this.esignId;
    }
    
    public void setEsignId(String esignId) {
        this.esignId = esignId;
    }

    
    @Column(name="esign_status_cd", length=20)
    public String getEsignStatusCd() {
        return this.esignStatusCd;
    }
    
    public void setEsignStatusCd(String esignStatusCd) {
        this.esignStatusCd = esignStatusCd;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

    
    @Column(name="signed_at", length=50)
    public String getSignedAt() {
        return this.signedAt;
    }
    
    public void setSignedAt(String signedAt) {
        this.signedAt = signedAt;
    }

    
    @Column(name="esignorwetsign_ind", length=1)
    public Character getEsignorwetsignInd() {
        return this.esignorwetsignInd;
    }
    
    public void setEsignorwetsignInd(Character esignorwetsignInd) {
        this.esignorwetsignInd = esignorwetsignInd;
    }

    
    @Column(name="is_parent_present_tosign", length=1)
    public Character getIsParentPresentTosign() {
        return this.isParentPresentTosign;
    }
    
    public void setIsParentPresentTosign(Character isParentPresentTosign) {
        this.isParentPresentTosign = isParentPresentTosign;
    }




}


