package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CasePremiumMode generated by hbm2java
 */
@Entity
@Table(name="case_premium_mode"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class CasePremiumMode  implements java.io.Serializable {


     private Integer casePremiumModeId;
     private AppCase appCase;
     private ClientEftFinInstDetails clientEftFinInstDetails;
     private String billingModeCd;
     private String billingFormCd;
     private String comments;
     private String accountNumber;
     private BigDecimal modePremiumAmount;
     private String deductionDate;
     private Character minFiveEmployeeInd;
     private Character existingEftAccInd;
     private Integer eftDraftTimeId;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private Character modePremiumAmountInd;
     private Character addingPremiumDepositFund;
     private BigDecimal premiumDepositAmount;
     private Character policyOwnerDeclaration;

    public CasePremiumMode() {
    }

	
    public CasePremiumMode(AppCase appCase, char isDeletedInd, Date lstUpdtDtm) {
        this.appCase = appCase;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public CasePremiumMode(AppCase appCase, ClientEftFinInstDetails clientEftFinInstDetails, String billingModeCd, String billingFormCd, String comments, String accountNumber, BigDecimal modePremiumAmount, String deductionDate, Character minFiveEmployeeInd, Character existingEftAccInd, Integer eftDraftTimeId, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Character modePremiumAmountInd, Character addingPremiumDepositFund, BigDecimal premiumDepositAmount, Character policyOwnerDeclaration) {
       this.appCase = appCase;
       this.clientEftFinInstDetails = clientEftFinInstDetails;
       this.billingModeCd = billingModeCd;
       this.billingFormCd = billingFormCd;
       this.comments = comments;
       this.accountNumber = accountNumber;
       this.modePremiumAmount = modePremiumAmount;
       this.deductionDate = deductionDate;
       this.minFiveEmployeeInd = minFiveEmployeeInd;
       this.existingEftAccInd = existingEftAccInd;
       this.eftDraftTimeId = eftDraftTimeId;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.modePremiumAmountInd = modePremiumAmountInd;
       this.addingPremiumDepositFund = addingPremiumDepositFund;
       this.premiumDepositAmount = premiumDepositAmount;
       this.policyOwnerDeclaration = policyOwnerDeclaration;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="case_premium_mode_id", unique=true, nullable=false)
    public Integer getCasePremiumModeId() {
        return this.casePremiumModeId;
    }
    
    public void setCasePremiumModeId(Integer casePremiumModeId) {
        this.casePremiumModeId = casePremiumModeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_id", nullable=false)
    public AppCase getAppCase() {
        return this.appCase;
    }
    
    public void setAppCase(AppCase appCase) {
        this.appCase = appCase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_eft_fin_inst_details_id")
    public ClientEftFinInstDetails getClientEftFinInstDetails() {
        return this.clientEftFinInstDetails;
    }
    
    public void setClientEftFinInstDetails(ClientEftFinInstDetails clientEftFinInstDetails) {
        this.clientEftFinInstDetails = clientEftFinInstDetails;
    }

    
    @Column(name="billing_mode_cd", length=20)
    public String getBillingModeCd() {
        return this.billingModeCd;
    }
    
    public void setBillingModeCd(String billingModeCd) {
        this.billingModeCd = billingModeCd;
    }

    
    @Column(name="billing_form_cd", length=20)
    public String getBillingFormCd() {
        return this.billingFormCd;
    }
    
    public void setBillingFormCd(String billingFormCd) {
        this.billingFormCd = billingFormCd;
    }

    
    @Column(name="comments", length=500)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="account_number", length=20)
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    
    @Column(name="mode_premium_amount", precision=18)
    public BigDecimal getModePremiumAmount() {
        return this.modePremiumAmount;
    }
    
    public void setModePremiumAmount(BigDecimal modePremiumAmount) {
        this.modePremiumAmount = modePremiumAmount;
    }

    
    @Column(name="deduction_date", length=20)
    public String getDeductionDate() {
        return this.deductionDate;
    }
    
    public void setDeductionDate(String deductionDate) {
        this.deductionDate = deductionDate;
    }

    
    @Column(name="min_five_employee_ind", length=1)
    public Character getMinFiveEmployeeInd() {
        return this.minFiveEmployeeInd;
    }
    
    public void setMinFiveEmployeeInd(Character minFiveEmployeeInd) {
        this.minFiveEmployeeInd = minFiveEmployeeInd;
    }

    
    @Column(name="existing_eft_acc_ind", length=1)
    public Character getExistingEftAccInd() {
        return this.existingEftAccInd;
    }
    
    public void setExistingEftAccInd(Character existingEftAccInd) {
        this.existingEftAccInd = existingEftAccInd;
    }

    
    @Column(name="eft_draft_time_id")
    public Integer getEftDraftTimeId() {
        return this.eftDraftTimeId;
    }
    
    public void setEftDraftTimeId(Integer eftDraftTimeId) {
        this.eftDraftTimeId = eftDraftTimeId;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

    
    @Column(name="mode_premium_amount_ind", length=1)
    public Character getModePremiumAmountInd() {
        return this.modePremiumAmountInd;
    }
    
    public void setModePremiumAmountInd(Character modePremiumAmountInd) {
        this.modePremiumAmountInd = modePremiumAmountInd;
    }

    
    @Column(name="adding_premium_deposit_fund", length=1)
    public Character getAddingPremiumDepositFund() {
        return this.addingPremiumDepositFund;
    }
    
    public void setAddingPremiumDepositFund(Character addingPremiumDepositFund) {
        this.addingPremiumDepositFund = addingPremiumDepositFund;
    }

    
    @Column(name="premium_deposit_amount", precision=18)
    public BigDecimal getPremiumDepositAmount() {
        return this.premiumDepositAmount;
    }
    
    public void setPremiumDepositAmount(BigDecimal premiumDepositAmount) {
        this.premiumDepositAmount = premiumDepositAmount;
    }

    
    @Column(name="policy_owner_declaration", length=1)
    public Character getPolicyOwnerDeclaration() {
        return this.policyOwnerDeclaration;
    }
    
    public void setPolicyOwnerDeclaration(Character policyOwnerDeclaration) {
        this.policyOwnerDeclaration = policyOwnerDeclaration;
    }




}


