package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientEftFinInstDetails generated by hbm2java
 */
@Entity
@Table(name="client_eft_fin_inst_details"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class ClientEftFinInstDetails  implements java.io.Serializable {


     private Integer clientEftFinInstDetailsId;
     private ClientDetails clientDetails;
     private Integer financialInstitutionTypeId;
     private String financialInstitutionName;
     private Integer financialAccountTypeId;
     private String financialAccountTypeOther;
     private String financialAccountNumber;
     private Integer financialInstitutionUniqueId;
     private String financialInstitutionUniqueIdValue;
     private Character isActive;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private Set<ClientEftFinInstMap> clientEftFinInstMaps = new HashSet<ClientEftFinInstMap>(0);
     private Set<CasePremiumMode> casePremiumModes = new HashSet<CasePremiumMode>(0);

    public ClientEftFinInstDetails() {
    }

	
    public ClientEftFinInstDetails(ClientDetails clientDetails, char isDeletedInd, Date lstUpdtDtm) {
        this.clientDetails = clientDetails;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public ClientEftFinInstDetails(ClientDetails clientDetails, Integer financialInstitutionTypeId, String financialInstitutionName, Integer financialAccountTypeId, String financialAccountTypeOther, String financialAccountNumber, Integer financialInstitutionUniqueId, String financialInstitutionUniqueIdValue, Character isActive, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Set<ClientEftFinInstMap> clientEftFinInstMaps, Set<CasePremiumMode> casePremiumModes) {
       this.clientDetails = clientDetails;
       this.financialInstitutionTypeId = financialInstitutionTypeId;
       this.financialInstitutionName = financialInstitutionName;
       this.financialAccountTypeId = financialAccountTypeId;
       this.financialAccountTypeOther = financialAccountTypeOther;
       this.financialAccountNumber = financialAccountNumber;
       this.financialInstitutionUniqueId = financialInstitutionUniqueId;
       this.financialInstitutionUniqueIdValue = financialInstitutionUniqueIdValue;
       this.isActive = isActive;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.clientEftFinInstMaps = clientEftFinInstMaps;
       this.casePremiumModes = casePremiumModes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="client_eft_fin_inst_details_id", unique=true, nullable=false)
    public Integer getClientEftFinInstDetailsId() {
        return this.clientEftFinInstDetailsId;
    }
    
    public void setClientEftFinInstDetailsId(Integer clientEftFinInstDetailsId) {
        this.clientEftFinInstDetailsId = clientEftFinInstDetailsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_details_id", nullable=false)
    public ClientDetails getClientDetails() {
        return this.clientDetails;
    }
    
    public void setClientDetails(ClientDetails clientDetails) {
        this.clientDetails = clientDetails;
    }

    
    @Column(name="financial_institution_type_id")
    public Integer getFinancialInstitutionTypeId() {
        return this.financialInstitutionTypeId;
    }
    
    public void setFinancialInstitutionTypeId(Integer financialInstitutionTypeId) {
        this.financialInstitutionTypeId = financialInstitutionTypeId;
    }

    
    @Column(name="financial_institution_name", length=200)
    public String getFinancialInstitutionName() {
        return this.financialInstitutionName;
    }
    
    public void setFinancialInstitutionName(String financialInstitutionName) {
        this.financialInstitutionName = financialInstitutionName;
    }

    
    @Column(name="financial_account_type_id")
    public Integer getFinancialAccountTypeId() {
        return this.financialAccountTypeId;
    }
    
    public void setFinancialAccountTypeId(Integer financialAccountTypeId) {
        this.financialAccountTypeId = financialAccountTypeId;
    }

    
    @Column(name="financial_account_type_other", length=50)
    public String getFinancialAccountTypeOther() {
        return this.financialAccountTypeOther;
    }
    
    public void setFinancialAccountTypeOther(String financialAccountTypeOther) {
        this.financialAccountTypeOther = financialAccountTypeOther;
    }

    
    @Column(name="financial_account_number", length=20)
    public String getFinancialAccountNumber() {
        return this.financialAccountNumber;
    }
    
    public void setFinancialAccountNumber(String financialAccountNumber) {
        this.financialAccountNumber = financialAccountNumber;
    }

    
    @Column(name="financial_institution_unique_id")
    public Integer getFinancialInstitutionUniqueId() {
        return this.financialInstitutionUniqueId;
    }
    
    public void setFinancialInstitutionUniqueId(Integer financialInstitutionUniqueId) {
        this.financialInstitutionUniqueId = financialInstitutionUniqueId;
    }

    
    @Column(name="financial_institution_unique_id_value", length=50)
    public String getFinancialInstitutionUniqueIdValue() {
        return this.financialInstitutionUniqueIdValue;
    }
    
    public void setFinancialInstitutionUniqueIdValue(String financialInstitutionUniqueIdValue) {
        this.financialInstitutionUniqueIdValue = financialInstitutionUniqueIdValue;
    }

    
    @Column(name="is_active", length=1)
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientEftFinInstDetails")
    public Set<ClientEftFinInstMap> getClientEftFinInstMaps() {
        return this.clientEftFinInstMaps;
    }
    
    public void setClientEftFinInstMaps(Set<ClientEftFinInstMap> clientEftFinInstMaps) {
        this.clientEftFinInstMaps = clientEftFinInstMaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientEftFinInstDetails")
    public Set<CasePremiumMode> getCasePremiumModes() {
        return this.casePremiumModes;
    }
    
    public void setCasePremiumModes(Set<CasePremiumMode> casePremiumModes) {
        this.casePremiumModes = casePremiumModes;
    }




}


