package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * ClientEftFinInstMap generated by hbm2java
 */
@Entity
@Table(name = "client_eft_fin_inst_map")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ClientEftFinInstMap implements java.io.Serializable {

	private Integer clientEftFinInstMapId;
	private ClientEftFinInstDetails clientEftFinInstDetails;
	private String firstNm;
	private String lastNm;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public ClientEftFinInstMap() {
	}

	public ClientEftFinInstMap(ClientEftFinInstDetails clientEftFinInstDetails, char isDeletedInd, Date lstUpdtDtm) {
		this.clientEftFinInstDetails = clientEftFinInstDetails;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public ClientEftFinInstMap(ClientEftFinInstDetails clientEftFinInstDetails, String firstNm, String lastNm,
			char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
		this.clientEftFinInstDetails = clientEftFinInstDetails;
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "client_eft_fin_inst_map_id", unique = true, nullable = false)
	public Integer getClientEftFinInstMapId() {
		return this.clientEftFinInstMapId;
	}

	public void setClientEftFinInstMapId(Integer clientEftFinInstMapId) {
		this.clientEftFinInstMapId = clientEftFinInstMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_eft_fin_inst_details_id", nullable = false)
	public ClientEftFinInstDetails getClientEftFinInstDetails() {
		return this.clientEftFinInstDetails;
	}

	public void setClientEftFinInstDetails(ClientEftFinInstDetails clientEftFinInstDetails) {
		this.clientEftFinInstDetails = clientEftFinInstDetails;
	}

	@Column(name = "first_nm", length = 50)
	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	@Column(name = "last_nm", length = 50)
	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
