package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientDetails generated by hbm2java
 */
@Entity
@Table(name="client_details"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class ClientDetails  implements java.io.Serializable {


     private Integer clientDetailsId;
     private long tenantId;
     private Date dob;
     private String firstNm;
     private String middleNm;
     private String lastNm;
     private String prefixCd;
     private String suffixCd;
     private String birthCountryCd;
     private String birthStateCd;
     private Character genderCd;
     private String clientUniqueIdTypeCd;
     private String clientUniqueIdValue;
     private String clientTypeCd;
     private Date dateOfTrust;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private Integer cloningCaseId;
     private Character cloningStakeholderType;
     private String cloningPartySelectedInScreen;
     private String isPartySameAs;
     private String crmClientId;
     private String crmOprtnyId;
     private String inptDob;
     private Set<CaseClientMap> caseClientMaps = new HashSet<CaseClientMap>(0);
     private Set<ClientEftFinInstDetails> clientEftFinInstDetailses = new HashSet<ClientEftFinInstDetails>(0);

    public ClientDetails() {
    }

	
    public ClientDetails(long tenantId) {
        this.tenantId = tenantId;
    }
    public ClientDetails(long tenantId, Date dob, String firstNm, String middleNm, String lastNm, String prefixCd, String suffixCd, String birthCountryCd, String birthStateCd, Character genderCd, String clientUniqueIdTypeCd, String clientUniqueIdValue, String clientTypeCd, Date dateOfTrust, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Integer cloningCaseId, Character cloningStakeholderType, String cloningPartySelectedInScreen, String isPartySameAs, String crmClientId, String crmOprtnyId, String inptDob, Set<CaseClientMap> caseClientMaps, Set<ClientEftFinInstDetails> clientEftFinInstDetailses) {
       this.tenantId = tenantId;
       this.dob = dob;
       this.firstNm = firstNm;
       this.middleNm = middleNm;
       this.lastNm = lastNm;
       this.prefixCd = prefixCd;
       this.suffixCd = suffixCd;
       this.birthCountryCd = birthCountryCd;
       this.birthStateCd = birthStateCd;
       this.genderCd = genderCd;
       this.clientUniqueIdTypeCd = clientUniqueIdTypeCd;
       this.clientUniqueIdValue = clientUniqueIdValue;
       this.clientTypeCd = clientTypeCd;
       this.dateOfTrust = dateOfTrust;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.cloningCaseId = cloningCaseId;
       this.cloningStakeholderType = cloningStakeholderType;
       this.cloningPartySelectedInScreen = cloningPartySelectedInScreen;
       this.isPartySameAs = isPartySameAs;
       this.crmClientId = crmClientId;
       this.crmOprtnyId = crmOprtnyId;
       this.inptDob = inptDob;
       this.caseClientMaps = caseClientMaps;
       this.clientEftFinInstDetailses = clientEftFinInstDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="client_details_id", unique=true, nullable=false)
    public Integer getClientDetailsId() {
        return this.clientDetailsId;
    }
    
    public void setClientDetailsId(Integer clientDetailsId) {
        this.clientDetailsId = clientDetailsId;
    }

    
    @Column(name="tenant_id", nullable=false)
    public long getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(long tenantId) {
        this.tenantId = tenantId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dob", length=23)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="first_nm", length=50)
    public String getFirstNm() {
        return this.firstNm;
    }
    
    public void setFirstNm(String firstNm) {
        this.firstNm = firstNm;
    }

    
    @Column(name="middle_nm", length=50)
    public String getMiddleNm() {
        return this.middleNm;
    }
    
    public void setMiddleNm(String middleNm) {
        this.middleNm = middleNm;
    }

    
    @Column(name="last_nm", length=50)
    public String getLastNm() {
        return this.lastNm;
    }
    
    public void setLastNm(String lastNm) {
        this.lastNm = lastNm;
    }

    
    @Column(name="prefix_cd", length=8)
    public String getPrefixCd() {
        return this.prefixCd;
    }
    
    public void setPrefixCd(String prefixCd) {
        this.prefixCd = prefixCd;
    }

    
    @Column(name="suffix_cd", length=8)
    public String getSuffixCd() {
        return this.suffixCd;
    }
    
    public void setSuffixCd(String suffixCd) {
        this.suffixCd = suffixCd;
    }

    
    @Column(name="birth_country_cd", length=3)
    public String getBirthCountryCd() {
        return this.birthCountryCd;
    }
    
    public void setBirthCountryCd(String birthCountryCd) {
        this.birthCountryCd = birthCountryCd;
    }

    
    @Column(name="birth_state_cd", length=50)
    public String getBirthStateCd() {
        return this.birthStateCd;
    }
    
    public void setBirthStateCd(String birthStateCd) {
        this.birthStateCd = birthStateCd;
    }

    
    @Column(name="gender_cd", length=1)
    public Character getGenderCd() {
        return this.genderCd;
    }
    
    public void setGenderCd(Character genderCd) {
        this.genderCd = genderCd;
    }

    
    @Column(name="client_unique_id_type_cd", length=25)
    public String getClientUniqueIdTypeCd() {
        return this.clientUniqueIdTypeCd;
    }
    
    public void setClientUniqueIdTypeCd(String clientUniqueIdTypeCd) {
        this.clientUniqueIdTypeCd = clientUniqueIdTypeCd;
    }

    
    @Column(name="client_unique_id_value", length=50)
    public String getClientUniqueIdValue() {
        return this.clientUniqueIdValue;
    }
    
    public void setClientUniqueIdValue(String clientUniqueIdValue) {
        this.clientUniqueIdValue = clientUniqueIdValue;
    }

    
    @Column(name="client_type_cd", length=8)
    public String getClientTypeCd() {
        return this.clientTypeCd;
    }
    
    public void setClientTypeCd(String clientTypeCd) {
        this.clientTypeCd = clientTypeCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_trust", length=23)
    public Date getDateOfTrust() {
        return this.dateOfTrust;
    }
    
    public void setDateOfTrust(Date dateOfTrust) {
        this.dateOfTrust = dateOfTrust;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

    
    @Column(name="cloning_case_id")
    public Integer getCloningCaseId() {
        return this.cloningCaseId;
    }
    
    public void setCloningCaseId(Integer cloningCaseId) {
        this.cloningCaseId = cloningCaseId;
    }

    
    @Column(name="cloning_stakeholder_type", length=1)
    public Character getCloningStakeholderType() {
        return this.cloningStakeholderType;
    }
    
    public void setCloningStakeholderType(Character cloningStakeholderType) {
        this.cloningStakeholderType = cloningStakeholderType;
    }

    
    @Column(name="cloning_party_selected_in_screen", length=50)
    public String getCloningPartySelectedInScreen() {
        return this.cloningPartySelectedInScreen;
    }
    
    public void setCloningPartySelectedInScreen(String cloningPartySelectedInScreen) {
        this.cloningPartySelectedInScreen = cloningPartySelectedInScreen;
    }

    
    @Column(name="isPartySameAs")
    public String getIsPartySameAs() {
        return this.isPartySameAs;
    }
    
    public void setIsPartySameAs(String isPartySameAs) {
        this.isPartySameAs = isPartySameAs;
    }

    
    @Column(name="crm_client_id", length=50)
    public String getCrmClientId() {
        return this.crmClientId;
    }
    
    public void setCrmClientId(String crmClientId) {
        this.crmClientId = crmClientId;
    }

    
    @Column(name="crm_oprtny_id", length=50)
    public String getCrmOprtnyId() {
        return this.crmOprtnyId;
    }
    
    public void setCrmOprtnyId(String crmOprtnyId) {
        this.crmOprtnyId = crmOprtnyId;
    }

    
    @Column(name="inpt_dob", length=30)
    public String getInptDob() {
        return this.inptDob;
    }
    
    public void setInptDob(String inptDob) {
        this.inptDob = inptDob;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientDetails")
    public Set<CaseClientMap> getCaseClientMaps() {
        return this.caseClientMaps;
    }
    
    public void setCaseClientMaps(Set<CaseClientMap> caseClientMaps) {
        this.caseClientMaps = caseClientMaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientDetails")
    public Set<ClientEftFinInstDetails> getClientEftFinInstDetailses() {
        return this.clientEftFinInstDetailses;
    }
    
    public void setClientEftFinInstDetailses(Set<ClientEftFinInstDetails> clientEftFinInstDetailses) {
        this.clientEftFinInstDetailses = clientEftFinInstDetailses;
    }




}


