package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * ClientUniqueIdType generated by hbm2java
 */
@Entity
@Table(name = "client_unique_id_type")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ClientUniqueIdType implements java.io.Serializable {

	private String clientUniqueIdTypeCd;
	private String clientUniqueIdTypeDesc;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public ClientUniqueIdType() {
	}

	public ClientUniqueIdType(String clientUniqueIdTypeCd, char isDeletedInd, Date lstUpdtDtm) {
		this.clientUniqueIdTypeCd = clientUniqueIdTypeCd;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public ClientUniqueIdType(String clientUniqueIdTypeCd, String clientUniqueIdTypeDesc, char isDeletedInd,
			String lstUpdtUserId, Date lstUpdtDtm) {
		this.clientUniqueIdTypeCd = clientUniqueIdTypeCd;
		this.clientUniqueIdTypeDesc = clientUniqueIdTypeDesc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "client_unique_id_type_cd", unique = true, nullable = false, length = 25)
	public String getClientUniqueIdTypeCd() {
		return this.clientUniqueIdTypeCd;
	}

	public void setClientUniqueIdTypeCd(String clientUniqueIdTypeCd) {
		this.clientUniqueIdTypeCd = clientUniqueIdTypeCd;
	}

	@Column(name = "client_unique_id_type_desc", length = 50)
	public String getClientUniqueIdTypeDesc() {
		return this.clientUniqueIdTypeDesc;
	}

	public void setClientUniqueIdTypeDesc(String clientUniqueIdTypeDesc) {
		this.clientUniqueIdTypeDesc = clientUniqueIdTypeDesc;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
