package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EntityListeners;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * CloningPartyscreenDetailsId generated by hbm2java
 */
@Embeddable
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class CloningPartyscreenDetailsId implements java.io.Serializable {

	private int seqNum;
	private Integer currentCaseId;
	private String newApplicationType;
	private String newCaseType;
	private String partiesStakeholderTypeList;
	private String screenCloningList;
	private Integer clonedCaseId;
	private Date lstUpdtDtm;

	public CloningPartyscreenDetailsId() {
	}

	public CloningPartyscreenDetailsId(int seqNum, Date lstUpdtDtm) {
		this.seqNum = seqNum;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public CloningPartyscreenDetailsId(int seqNum, Integer currentCaseId, String newApplicationType, String newCaseType,
			String partiesStakeholderTypeList, String screenCloningList, Integer clonedCaseId, Date lstUpdtDtm) {
		this.seqNum = seqNum;
		this.currentCaseId = currentCaseId;
		this.newApplicationType = newApplicationType;
		this.newCaseType = newCaseType;
		this.partiesStakeholderTypeList = partiesStakeholderTypeList;
		this.screenCloningList = screenCloningList;
		this.clonedCaseId = clonedCaseId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "seq_num", nullable = false)
	public int getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "current_case_id")
	public Integer getCurrentCaseId() {
		return this.currentCaseId;
	}

	public void setCurrentCaseId(Integer currentCaseId) {
		this.currentCaseId = currentCaseId;
	}

	@Column(name = "new_applicationType")
	public String getNewApplicationType() {
		return this.newApplicationType;
	}

	public void setNewApplicationType(String newApplicationType) {
		this.newApplicationType = newApplicationType;
	}

	@Column(name = "new_caseType")
	public String getNewCaseType() {
		return this.newCaseType;
	}

	public void setNewCaseType(String newCaseType) {
		this.newCaseType = newCaseType;
	}

	@Column(name = "parties_StakeholderTypeList")
	public String getPartiesStakeholderTypeList() {
		return this.partiesStakeholderTypeList;
	}

	public void setPartiesStakeholderTypeList(String partiesStakeholderTypeList) {
		this.partiesStakeholderTypeList = partiesStakeholderTypeList;
	}

	@Column(name = "ScreenCloningList")
	public String getScreenCloningList() {
		return this.screenCloningList;
	}

	public void setScreenCloningList(String screenCloningList) {
		this.screenCloningList = screenCloningList;
	}

	@Column(name = "clonedCaseID")
	public Integer getClonedCaseId() {
		return this.clonedCaseId;
	}

	public void setClonedCaseId(Integer clonedCaseId) {
		this.clonedCaseId = clonedCaseId;
	}

	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CloningPartyscreenDetailsId))
			return false;
		CloningPartyscreenDetailsId castOther = (CloningPartyscreenDetailsId) other;

		return (this.getSeqNum() == castOther.getSeqNum())
				&& ((this.getCurrentCaseId() == castOther.getCurrentCaseId())
						|| (this.getCurrentCaseId() != null && castOther.getCurrentCaseId() != null
								&& this.getCurrentCaseId().equals(castOther.getCurrentCaseId())))
				&& ((this.getNewApplicationType() == castOther.getNewApplicationType())
						|| (this.getNewApplicationType() != null && castOther.getNewApplicationType() != null
								&& this.getNewApplicationType().equals(castOther.getNewApplicationType())))
				&& ((this.getNewCaseType() == castOther.getNewCaseType())
						|| (this.getNewCaseType() != null && castOther.getNewCaseType() != null
								&& this.getNewCaseType().equals(castOther.getNewCaseType())))
				&& ((this.getPartiesStakeholderTypeList() == castOther.getPartiesStakeholderTypeList())
						|| (this.getPartiesStakeholderTypeList() != null
								&& castOther.getPartiesStakeholderTypeList() != null
								&& this.getPartiesStakeholderTypeList()
										.equals(castOther.getPartiesStakeholderTypeList())))
				&& ((this.getScreenCloningList() == castOther.getScreenCloningList())
						|| (this.getScreenCloningList() != null && castOther.getScreenCloningList() != null
								&& this.getScreenCloningList().equals(castOther.getScreenCloningList())))
				&& ((this.getClonedCaseId() == castOther.getClonedCaseId())
						|| (this.getClonedCaseId() != null && castOther.getClonedCaseId() != null
								&& this.getClonedCaseId().equals(castOther.getClonedCaseId())))
				&& ((this.getLstUpdtDtm() == castOther.getLstUpdtDtm())
						|| (this.getLstUpdtDtm() != null && castOther.getLstUpdtDtm() != null
								&& this.getLstUpdtDtm().equals(castOther.getLstUpdtDtm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeqNum();
		result = 37 * result + (getCurrentCaseId() == null ? 0 : this.getCurrentCaseId().hashCode());
		result = 37 * result + (getNewApplicationType() == null ? 0 : this.getNewApplicationType().hashCode());
		result = 37 * result + (getNewCaseType() == null ? 0 : this.getNewCaseType().hashCode());
		result = 37 * result
				+ (getPartiesStakeholderTypeList() == null ? 0 : this.getPartiesStakeholderTypeList().hashCode());
		result = 37 * result + (getScreenCloningList() == null ? 0 : this.getScreenCloningList().hashCode());
		result = 37 * result + (getClonedCaseId() == null ? 0 : this.getClonedCaseId().hashCode());
		result = 37 * result + (getLstUpdtDtm() == null ? 0 : this.getLstUpdtDtm().hashCode());
		return result;
	}

}
