package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Combtwo generated by hbm2java
 */
@Entity
@Table(name = "combtwo")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Combtwo implements java.io.Serializable {

	private int combId;
	private Companytable companytable;
	private Usertable usertable;
	private String mergeName;

	public Combtwo() {
	}

	public Combtwo(int combId, Companytable companytable, Usertable usertable, String mergeName) {
		this.combId = combId;
		this.companytable = companytable;
		this.usertable = usertable;
		this.mergeName = mergeName;
	}

	@Id

	@Column(name = "comb_id", unique = true, nullable = false)
	public int getCombId() {
		return this.combId;
	}

	public void setCombId(int combId) {
		this.combId = combId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comp_id", nullable = false)
	public Companytable getCompanytable() {
		return this.companytable;
	}

	public void setCompanytable(Companytable companytable) {
		this.companytable = companytable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false)
	public Usertable getUsertable() {
		return this.usertable;
	}

	public void setUsertable(Usertable usertable) {
		this.usertable = usertable;
	}

	@Column(name = "merge_name", nullable = false, length = 40)
	public String getMergeName() {
		return this.mergeName;
	}

	public void setMergeName(String mergeName) {
		this.mergeName = mergeName;
	}

}
