package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Company implements java.io.Serializable {

	private int companyId;
	private String companyCd;
	private String companyNm;
	private Integer archivingDays;
	private String archivingPath;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private Integer parentCompanyId;
	private Character setupAllowInd;

	public Company() {
	}

	public Company(int companyId, String companyCd, String companyNm, char isDeletedInd, Date lstUpdtDtm) {
		this.companyId = companyId;
		this.companyCd = companyCd;
		this.companyNm = companyNm;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public Company(int companyId, String companyCd, String companyNm, Integer archivingDays, String archivingPath,
			char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Integer parentCompanyId,
			Character setupAllowInd) {
		this.companyId = companyId;
		this.companyCd = companyCd;
		this.companyNm = companyNm;
		this.archivingDays = archivingDays;
		this.archivingPath = archivingPath;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.parentCompanyId = parentCompanyId;
		this.setupAllowInd = setupAllowInd;
	}

	@Id

	@Column(name = "company_id", unique = true, nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "company_cd", nullable = false, length = 8)
	public String getCompanyCd() {
		return this.companyCd;
	}

	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	@Column(name = "company_nm", nullable = false, length = 100)
	public String getCompanyNm() {
		return this.companyNm;
	}

	public void setCompanyNm(String companyNm) {
		this.companyNm = companyNm;
	}

	@Column(name = "archiving_days")
	public Integer getArchivingDays() {
		return this.archivingDays;
	}

	public void setArchivingDays(Integer archivingDays) {
		this.archivingDays = archivingDays;
	}

	@Column(name = "archiving_path", length = 100)
	public String getArchivingPath() {
		return this.archivingPath;
	}

	public void setArchivingPath(String archivingPath) {
		this.archivingPath = archivingPath;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "parent_company_id")
	public Integer getParentCompanyId() {
		return this.parentCompanyId;
	}

	public void setParentCompanyId(Integer parentCompanyId) {
		this.parentCompanyId = parentCompanyId;
	}

	@Column(name = "setup_allow_ind", length = 1)
	public Character getSetupAllowInd() {
		return this.setupAllowInd;
	}

	public void setSetupAllowInd(Character setupAllowInd) {
		this.setupAllowInd = setupAllowInd;
	}

}
