package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * DeathBenefitOption generated by hbm2java
 */
@Entity
@Table(name = "death_benefit_option")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class DeathBenefitOption implements java.io.Serializable {

	private String deathBenefitOptionCd;
	private String deathBenefitOptionDesc;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public DeathBenefitOption() {
	}

	public DeathBenefitOption(String deathBenefitOptionCd, char isDeletedInd, Date lstUpdtDtm) {
		this.deathBenefitOptionCd = deathBenefitOptionCd;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public DeathBenefitOption(String deathBenefitOptionCd, String deathBenefitOptionDesc, char isDeletedInd,
			String lstUpdtUserId, Date lstUpdtDtm) {
		this.deathBenefitOptionCd = deathBenefitOptionCd;
		this.deathBenefitOptionDesc = deathBenefitOptionDesc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "death_benefit_option_cd", unique = true, nullable = false, length = 50)
	public String getDeathBenefitOptionCd() {
		return this.deathBenefitOptionCd;
	}

	public void setDeathBenefitOptionCd(String deathBenefitOptionCd) {
		this.deathBenefitOptionCd = deathBenefitOptionCd;
	}

	@Column(name = "death_benefit_option_desc", length = 100)
	public String getDeathBenefitOptionDesc() {
		return this.deathBenefitOptionDesc;
	}

	public void setDeathBenefitOptionDesc(String deathBenefitOptionDesc) {
		this.deathBenefitOptionDesc = deathBenefitOptionDesc;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
