package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DividendOptionType generated by hbm2java
 */
@Entity
@Table(name="dividend_option_type"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class DividendOptionType  implements java.io.Serializable {


     private int divOptId;
     private String divOptNm;
     private String divOptDesc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public DividendOptionType() {
    }

	
    public DividendOptionType(int divOptId, String divOptNm, char isDeletedInd, Date lstUpdtDtm) {
        this.divOptId = divOptId;
        this.divOptNm = divOptNm;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public DividendOptionType(int divOptId, String divOptNm, String divOptDesc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.divOptId = divOptId;
       this.divOptNm = divOptNm;
       this.divOptDesc = divOptDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="div_opt_id", unique=true, nullable=false)
    public int getDivOptId() {
        return this.divOptId;
    }
    
    public void setDivOptId(int divOptId) {
        this.divOptId = divOptId;
    }

    
    @Column(name="div_opt_nm", nullable=false, length=100)
    public String getDivOptNm() {
        return this.divOptNm;
    }
    
    public void setDivOptNm(String divOptNm) {
        this.divOptNm = divOptNm;
    }

    
    @Column(name="div_opt_desc", length=250)
    public String getDivOptDesc() {
        return this.divOptDesc;
    }
    
    public void setDivOptDesc(String divOptDesc) {
        this.divOptDesc = divOptDesc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


