package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DynaUiScreen generated by hbm2java
 */
@Entity
@Table(name="dyna_ui_screen"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class DynaUiScreen  implements java.io.Serializable {


     private Integer id;
     private String screenNm;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private Set<DynaUiMapping> dynaUiMappings = new HashSet<DynaUiMapping>(0);
     private Set<DynaUiElements> dynaUiElementses = new HashSet<DynaUiElements>(0);

    public DynaUiScreen() {
    }

	
    public DynaUiScreen(String screenNm, char isDeletedInd, Date lstUpdtDtm) {
        this.screenNm = screenNm;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public DynaUiScreen(String screenNm, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Set<DynaUiMapping> dynaUiMappings, Set<DynaUiElements> dynaUiElementses) {
       this.screenNm = screenNm;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.dynaUiMappings = dynaUiMappings;
       this.dynaUiElementses = dynaUiElementses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="screen_nm", nullable=false, length=50)
    public String getScreenNm() {
        return this.screenNm;
    }
    
    public void setScreenNm(String screenNm) {
        this.screenNm = screenNm;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dynaUiScreen")
    public Set<DynaUiMapping> getDynaUiMappings() {
        return this.dynaUiMappings;
    }
    
    public void setDynaUiMappings(Set<DynaUiMapping> dynaUiMappings) {
        this.dynaUiMappings = dynaUiMappings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dynaUiScreen")
    public Set<DynaUiElements> getDynaUiElementses() {
        return this.dynaUiElementses;
    }
    
    public void setDynaUiElementses(Set<DynaUiElements> dynaUiElementses) {
        this.dynaUiElementses = dynaUiElementses;
    }




}


