package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * DynaUiElements generated by hbm2java
 */
@Entity
@Table(name = "dyna_ui_elements"

		, uniqueConstraints = @UniqueConstraint(columnNames = { "id", "screen_id" }))
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class DynaUiElements implements java.io.Serializable {

	private Integer id;
	private DynaUiScreen dynaUiScreen;
	private String uiElementNm;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private Set<DynaUiMapping> dynaUiMappings = new HashSet<DynaUiMapping>(0);

	public DynaUiElements() {
	}

	public DynaUiElements(DynaUiScreen dynaUiScreen, String uiElementNm, char isDeletedInd, Date lstUpdtDtm) {
		this.dynaUiScreen = dynaUiScreen;
		this.uiElementNm = uiElementNm;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public DynaUiElements(DynaUiScreen dynaUiScreen, String uiElementNm, char isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm, Set<DynaUiMapping> dynaUiMappings) {
		this.dynaUiScreen = dynaUiScreen;
		this.uiElementNm = uiElementNm;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.dynaUiMappings = dynaUiMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_id", nullable = false)
	public DynaUiScreen getDynaUiScreen() {
		return this.dynaUiScreen;
	}

	public void setDynaUiScreen(DynaUiScreen dynaUiScreen) {
		this.dynaUiScreen = dynaUiScreen;
	}

	@Column(name = "ui_element_nm", nullable = false, length = 50)
	public String getUiElementNm() {
		return this.uiElementNm;
	}

	public void setUiElementNm(String uiElementNm) {
		this.uiElementNm = uiElementNm;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dynaUiElements")
	public Set<DynaUiMapping> getDynaUiMappings() {
		return this.dynaUiMappings;
	}

	public void setDynaUiMappings(Set<DynaUiMapping> dynaUiMappings) {
		this.dynaUiMappings = dynaUiMappings;
	}

}
