package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DynaUiElements generated by hbm2java
 */
@Entity
@Table(name="dyna_ui_elements"
    ,schema="dbo"
    ,catalog="life_eapp"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id", "screen_id"}) 
)
public class DynaUiElements  implements java.io.Serializable {


     private Integer id;
     private DynaUiScreen dynaUiScreen;
     private String uiElementNm;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private Set<DynaUiMapping> dynaUiMappings = new HashSet<DynaUiMapping>(0);

    public DynaUiElements() {
    }

	
    public DynaUiElements(DynaUiScreen dynaUiScreen, String uiElementNm, char isDeletedInd, Date lstUpdtDtm) {
        this.dynaUiScreen = dynaUiScreen;
        this.uiElementNm = uiElementNm;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public DynaUiElements(DynaUiScreen dynaUiScreen, String uiElementNm, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Set<DynaUiMapping> dynaUiMappings) {
       this.dynaUiScreen = dynaUiScreen;
       this.uiElementNm = uiElementNm;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.dynaUiMappings = dynaUiMappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="screen_id", nullable=false)
    public DynaUiScreen getDynaUiScreen() {
        return this.dynaUiScreen;
    }
    
    public void setDynaUiScreen(DynaUiScreen dynaUiScreen) {
        this.dynaUiScreen = dynaUiScreen;
    }

    
    @Column(name="ui_element_nm", nullable=false, length=50)
    public String getUiElementNm() {
        return this.uiElementNm;
    }
    
    public void setUiElementNm(String uiElementNm) {
        this.uiElementNm = uiElementNm;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dynaUiElements")
    public Set<DynaUiMapping> getDynaUiMappings() {
        return this.dynaUiMappings;
    }
    
    public void setDynaUiMappings(Set<DynaUiMapping> dynaUiMappings) {
        this.dynaUiMappings = dynaUiMappings;
    }




}


