package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EappCaseRole generated by hbm2java
 */
@Entity
@Table(name="eapp_case_role"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class EappCaseRole  implements java.io.Serializable {


     private int eappCaseRoleId;
     private String eappCaseRoleCd;
     private String eappCaseRoleDsc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public EappCaseRole() {
    }

	
    public EappCaseRole(int eappCaseRoleId, char isDeletedInd, Date lstUpdtDtm) {
        this.eappCaseRoleId = eappCaseRoleId;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public EappCaseRole(int eappCaseRoleId, String eappCaseRoleCd, String eappCaseRoleDsc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.eappCaseRoleId = eappCaseRoleId;
       this.eappCaseRoleCd = eappCaseRoleCd;
       this.eappCaseRoleDsc = eappCaseRoleDsc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="eapp_case_role_id", unique=true, nullable=false)
    public int getEappCaseRoleId() {
        return this.eappCaseRoleId;
    }
    
    public void setEappCaseRoleId(int eappCaseRoleId) {
        this.eappCaseRoleId = eappCaseRoleId;
    }

    
    @Column(name="eapp_case_role_cd", length=20)
    public String getEappCaseRoleCd() {
        return this.eappCaseRoleCd;
    }
    
    public void setEappCaseRoleCd(String eappCaseRoleCd) {
        this.eappCaseRoleCd = eappCaseRoleCd;
    }

    
    @Column(name="eapp_case_role_dsc", length=50)
    public String getEappCaseRoleDsc() {
        return this.eappCaseRoleDsc;
    }
    
    public void setEappCaseRoleDsc(String eappCaseRoleDsc) {
        this.eappCaseRoleDsc = eappCaseRoleDsc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


