package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EappFormTemplateCriteria generated by hbm2java
 */
@Entity
@Table(name="eapp_form_template_criteria"
    ,schema="dbo"
    ,catalog="life_eapp"
    , uniqueConstraints = @UniqueConstraint(columnNames={"company_id", "prod_typ_cd", "case_typ_cd", "state_cd"}) 
)
public class EappFormTemplateCriteria  implements java.io.Serializable {


     private Integer id;
     private int companyId;
     private String prodTypCd;
     private String caseTypCd;
     private String stateCd;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private Set<EappFormTemplateMap> eappFormTemplateMaps = new HashSet<EappFormTemplateMap>(0);

    public EappFormTemplateCriteria() {
    }

	
    public EappFormTemplateCriteria(int companyId, String prodTypCd, String caseTypCd, String stateCd, char isDeletedInd, Date lstUpdtDtm) {
        this.companyId = companyId;
        this.prodTypCd = prodTypCd;
        this.caseTypCd = caseTypCd;
        this.stateCd = stateCd;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public EappFormTemplateCriteria(int companyId, String prodTypCd, String caseTypCd, String stateCd, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, Set<EappFormTemplateMap> eappFormTemplateMaps) {
       this.companyId = companyId;
       this.prodTypCd = prodTypCd;
       this.caseTypCd = caseTypCd;
       this.stateCd = stateCd;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.eappFormTemplateMaps = eappFormTemplateMaps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="company_id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="prod_typ_cd", nullable=false, length=8)
    public String getProdTypCd() {
        return this.prodTypCd;
    }
    
    public void setProdTypCd(String prodTypCd) {
        this.prodTypCd = prodTypCd;
    }

    
    @Column(name="case_typ_cd", nullable=false, length=8)
    public String getCaseTypCd() {
        return this.caseTypCd;
    }
    
    public void setCaseTypCd(String caseTypCd) {
        this.caseTypCd = caseTypCd;
    }

    
    @Column(name="state_cd", nullable=false, length=2)
    public String getStateCd() {
        return this.stateCd;
    }
    
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="eappFormTemplateCriteria")
    public Set<EappFormTemplateMap> getEappFormTemplateMaps() {
        return this.eappFormTemplateMaps;
    }
    
    public void setEappFormTemplateMaps(Set<EappFormTemplateMap> eappFormTemplateMaps) {
        this.eappFormTemplateMaps = eappFormTemplateMaps;
    }




}


