package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EftDraftTime generated by hbm2java
 */
@Entity
@Table(name="eft_draft_time"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class EftDraftTime  implements java.io.Serializable {


     private int eftDraftTimeId;
     private String eftDraftTimeDesc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public EftDraftTime() {
    }

	
    public EftDraftTime(int eftDraftTimeId, char isDeletedInd, Date lstUpdtDtm) {
        this.eftDraftTimeId = eftDraftTimeId;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public EftDraftTime(int eftDraftTimeId, String eftDraftTimeDesc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.eftDraftTimeId = eftDraftTimeId;
       this.eftDraftTimeDesc = eftDraftTimeDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="eft_draft_time_id", unique=true, nullable=false)
    public int getEftDraftTimeId() {
        return this.eftDraftTimeId;
    }
    
    public void setEftDraftTimeId(int eftDraftTimeId) {
        this.eftDraftTimeId = eftDraftTimeId;
    }

    
    @Column(name="eft_draft_time_desc", length=50)
    public String getEftDraftTimeDesc() {
        return this.eftDraftTimeDesc;
    }
    
    public void setEftDraftTimeDesc(String eftDraftTimeDesc) {
        this.eftDraftTimeDesc = eftDraftTimeDesc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


