package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Emp99 generated by hbm2java
 */
@Entity
@Table(name="Emp99"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class Emp99  implements java.io.Serializable {


     private Emp99Id id;

    public Emp99() {
    }

    public Emp99(Emp99Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="Id") ), 
        @AttributeOverride(name="name", column=@Column(name="Name", length=50) ), 
        @AttributeOverride(name="salary", column=@Column(name="Salary", precision=53, scale=0) ), 
        @AttributeOverride(name="designation", column=@Column(name="Designation", length=50) ) } )
    public Emp99Id getId() {
        return this.id;
    }
    
    public void setId(Emp99Id id) {
        this.id = id;
    }




}


