package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="Employee"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class Employee  implements java.io.Serializable {


     private EmployeeId id;

    public Employee() {
    }

    public Employee(EmployeeId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="name", column=@Column(name="name", length=50) ), 
        @AttributeOverride(name="email", column=@Column(name="email", length=50) ), 
        @AttributeOverride(name="address", column=@Column(name="address", length=50) ), 
        @AttributeOverride(name="telephone", column=@Column(name="telephone", length=50) ) } )
    public EmployeeId getId() {
        return this.id;
    }
    
    public void setId(EmployeeId id) {
        this.id = id;
    }




}


