package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinancialAccountType generated by hbm2java
 */
@Entity
@Table(name="financial_account_type"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class FinancialAccountType  implements java.io.Serializable {


     private int financialAccountTypeId;
     private String financialAccountTypeDesc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public FinancialAccountType() {
    }

	
    public FinancialAccountType(int financialAccountTypeId, char isDeletedInd, Date lstUpdtDtm) {
        this.financialAccountTypeId = financialAccountTypeId;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public FinancialAccountType(int financialAccountTypeId, String financialAccountTypeDesc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.financialAccountTypeId = financialAccountTypeId;
       this.financialAccountTypeDesc = financialAccountTypeDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="financial_account_type_id", unique=true, nullable=false)
    public int getFinancialAccountTypeId() {
        return this.financialAccountTypeId;
    }
    
    public void setFinancialAccountTypeId(int financialAccountTypeId) {
        this.financialAccountTypeId = financialAccountTypeId;
    }

    
    @Column(name="financial_account_type_desc", length=50)
    public String getFinancialAccountTypeDesc() {
        return this.financialAccountTypeDesc;
    }
    
    public void setFinancialAccountTypeDesc(String financialAccountTypeDesc) {
        this.financialAccountTypeDesc = financialAccountTypeDesc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


