package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinancialInstitutionUniqueIdentifier generated by hbm2java
 */
@Entity
@Table(name="financial_institution_unique_identifier"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class FinancialInstitutionUniqueIdentifier  implements java.io.Serializable {


     private int financialInstitutionUniqueId;
     private String financialInstitutionUniqueIdentifierDesc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public FinancialInstitutionUniqueIdentifier() {
    }

	
    public FinancialInstitutionUniqueIdentifier(int financialInstitutionUniqueId, char isDeletedInd, Date lstUpdtDtm) {
        this.financialInstitutionUniqueId = financialInstitutionUniqueId;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public FinancialInstitutionUniqueIdentifier(int financialInstitutionUniqueId, String financialInstitutionUniqueIdentifierDesc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.financialInstitutionUniqueId = financialInstitutionUniqueId;
       this.financialInstitutionUniqueIdentifierDesc = financialInstitutionUniqueIdentifierDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="financial_institution_unique_id", unique=true, nullable=false)
    public int getFinancialInstitutionUniqueId() {
        return this.financialInstitutionUniqueId;
    }
    
    public void setFinancialInstitutionUniqueId(int financialInstitutionUniqueId) {
        this.financialInstitutionUniqueId = financialInstitutionUniqueId;
    }

    
    @Column(name="financial_institution_unique_identifier_desc", length=50)
    public String getFinancialInstitutionUniqueIdentifierDesc() {
        return this.financialInstitutionUniqueIdentifierDesc;
    }
    
    public void setFinancialInstitutionUniqueIdentifierDesc(String financialInstitutionUniqueIdentifierDesc) {
        this.financialInstitutionUniqueIdentifierDesc = financialInstitutionUniqueIdentifierDesc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


