package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HouseholdT generated by hbm2java
 */
@Entity
@Table(name="household_t"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class HouseholdT  implements java.io.Serializable {


     private Integer householdId;
     private Integer clientId;
     private String firstNm;
     private String middleNm;
     private String lastNm;
     private String birthDate;
     private String gender;
     private String ssn;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;
     private String source;

    public HouseholdT() {
    }

	
    public HouseholdT(String source) {
        this.source = source;
    }
    public HouseholdT(Integer clientId, String firstNm, String middleNm, String lastNm, String birthDate, String gender, String ssn, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm, String source) {
       this.clientId = clientId;
       this.firstNm = firstNm;
       this.middleNm = middleNm;
       this.lastNm = lastNm;
       this.birthDate = birthDate;
       this.gender = gender;
       this.ssn = ssn;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
       this.source = source;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="household_id", unique=true, nullable=false)
    public Integer getHouseholdId() {
        return this.householdId;
    }
    
    public void setHouseholdId(Integer householdId) {
        this.householdId = householdId;
    }

    
    @Column(name="client_id")
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="first_nm", length=50)
    public String getFirstNm() {
        return this.firstNm;
    }
    
    public void setFirstNm(String firstNm) {
        this.firstNm = firstNm;
    }

    
    @Column(name="middle_nm", length=50)
    public String getMiddleNm() {
        return this.middleNm;
    }
    
    public void setMiddleNm(String middleNm) {
        this.middleNm = middleNm;
    }

    
    @Column(name="last_nm", length=50)
    public String getLastNm() {
        return this.lastNm;
    }
    
    public void setLastNm(String lastNm) {
        this.lastNm = lastNm;
    }

    
    @Column(name="birth_date", length=30)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="gender", length=15)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="ssn", length=50)
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }

    
    @Column(name="source", nullable=false, length=10)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }




}


