package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * LevelYear generated by hbm2java
 */
@Entity
@Table(name = "level_year")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class LevelYear implements java.io.Serializable {

	private int levelYearId;
	private int levelYearValue;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;
	private char isDeletedInd;

	public LevelYear() {
	}

	public LevelYear(int levelYearId, int levelYearValue, String lstUpdtUserId, Date lstUpdtDtm, char isDeletedInd) {
		this.levelYearId = levelYearId;
		this.levelYearValue = levelYearValue;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
		this.isDeletedInd = isDeletedInd;
	}

	@Id

	@Column(name = "level_year_id", unique = true, nullable = false)
	public int getLevelYearId() {
		return this.levelYearId;
	}

	public void setLevelYearId(int levelYearId) {
		this.levelYearId = levelYearId;
	}

	@Column(name = "level_year_value", nullable = false)
	public int getLevelYearValue() {
		return this.levelYearValue;
	}

	public void setLevelYearValue(int levelYearValue) {
		this.levelYearValue = levelYearValue;
	}

	@Column(name = "lst_updt_user_id", nullable = false, length = 20)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

}
