package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * LineOfBusiness generated by hbm2java
 */
@Entity
@Table(name = "line_of_business")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class LineOfBusiness implements java.io.Serializable {

	private String linOfBusinCd;
	private String linOfBusinDsc;
	private char isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public LineOfBusiness() {
	}

	public LineOfBusiness(String linOfBusinCd, char isDeletedInd, Date lstUpdtDtm) {
		this.linOfBusinCd = linOfBusinCd;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public LineOfBusiness(String linOfBusinCd, String linOfBusinDsc, char isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm) {
		this.linOfBusinCd = linOfBusinCd;
		this.linOfBusinDsc = linOfBusinDsc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "lin_of_busin_cd", unique = true, nullable = false, length = 8)
	public String getLinOfBusinCd() {
		return this.linOfBusinCd;
	}

	public void setLinOfBusinCd(String linOfBusinCd) {
		this.linOfBusinCd = linOfBusinCd;
	}

	@Column(name = "lin_of_busin_dsc", length = 250)
	public String getLinOfBusinDsc() {
		return this.linOfBusinDsc;
	}

	public void setLinOfBusinDsc(String linOfBusinDsc) {
		this.linOfBusinDsc = linOfBusinDsc;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
