package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * NamePrefix generated by hbm2java
 */
@Entity
@Table(name = "name_prefix")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class NamePrefix implements java.io.Serializable {

	private String nmPrefixCd;
	private String nmPrefixDsc;
	private Character isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public NamePrefix() {
	}

	public NamePrefix(String nmPrefixCd) {
		this.nmPrefixCd = nmPrefixCd;
	}

	public NamePrefix(String nmPrefixCd, String nmPrefixDsc, Character isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm) {
		this.nmPrefixCd = nmPrefixCd;
		this.nmPrefixDsc = nmPrefixDsc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "nm_prefix_cd", unique = true, nullable = false, length = 8)
	public String getNmPrefixCd() {
		return this.nmPrefixCd;
	}

	public void setNmPrefixCd(String nmPrefixCd) {
		this.nmPrefixCd = nmPrefixCd;
	}

	@Column(name = "nm_prefix_dsc", length = 20)
	public String getNmPrefixDsc() {
		return this.nmPrefixDsc;
	}

	public void setNmPrefixDsc(String nmPrefixDsc) {
		this.nmPrefixDsc = nmPrefixDsc;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
