package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * NicotineType generated by hbm2java
 */
@Entity
@Table(name = "nicotine_type")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class NicotineType implements java.io.Serializable {

	private String nicotineTypeCd;
	private String nicotineTypeDesc;
	private Character isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public NicotineType() {
	}

	public NicotineType(String nicotineTypeCd, String nicotineTypeDesc) {
		this.nicotineTypeCd = nicotineTypeCd;
		this.nicotineTypeDesc = nicotineTypeDesc;
	}

	public NicotineType(String nicotineTypeCd, String nicotineTypeDesc, Character isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm) {
		this.nicotineTypeCd = nicotineTypeCd;
		this.nicotineTypeDesc = nicotineTypeDesc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "nicotine_type_cd", unique = true, nullable = false, length = 8)
	public String getNicotineTypeCd() {
		return this.nicotineTypeCd;
	}

	public void setNicotineTypeCd(String nicotineTypeCd) {
		this.nicotineTypeCd = nicotineTypeCd;
	}

	@Column(name = "nicotine_type_desc", nullable = false, length = 50)
	public String getNicotineTypeDesc() {
		return this.nicotineTypeDesc;
	}

	public void setNicotineTypeDesc(String nicotineTypeDesc) {
		this.nicotineTypeDesc = nicotineTypeDesc;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
