package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * OwnerCategory generated by hbm2java
 */
@Entity
@Table(name = "owner_category")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class OwnerCategory implements java.io.Serializable {

	private String ownerCategoryCd;
	private String ownerCategoryDesc;
	private Character isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public OwnerCategory() {
	}

	public OwnerCategory(String ownerCategoryCd, String ownerCategoryDesc) {
		this.ownerCategoryCd = ownerCategoryCd;
		this.ownerCategoryDesc = ownerCategoryDesc;
	}

	public OwnerCategory(String ownerCategoryCd, String ownerCategoryDesc, Character isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm) {
		this.ownerCategoryCd = ownerCategoryCd;
		this.ownerCategoryDesc = ownerCategoryDesc;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "owner_category_cd", unique = true, nullable = false, length = 50)
	public String getOwnerCategoryCd() {
		return this.ownerCategoryCd;
	}

	public void setOwnerCategoryCd(String ownerCategoryCd) {
		this.ownerCategoryCd = ownerCategoryCd;
	}

	@Column(name = "owner_category_desc", nullable = false, length = 50)
	public String getOwnerCategoryDesc() {
		return this.ownerCategoryDesc;
	}

	public void setOwnerCategoryDesc(String ownerCategoryDesc) {
		this.ownerCategoryDesc = ownerCategoryDesc;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
