package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OwnerType generated by hbm2java
 */
@Entity
@Table(name="owner_type"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class OwnerType  implements java.io.Serializable {


     private String ownerTypeCd;
     private String ownerTypeDesc;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public OwnerType() {
    }

	
    public OwnerType(String ownerTypeCd, String ownerTypeDesc) {
        this.ownerTypeCd = ownerTypeCd;
        this.ownerTypeDesc = ownerTypeDesc;
    }
    public OwnerType(String ownerTypeCd, String ownerTypeDesc, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.ownerTypeCd = ownerTypeCd;
       this.ownerTypeDesc = ownerTypeDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="owner_type_cd", unique=true, nullable=false, length=50)
    public String getOwnerTypeCd() {
        return this.ownerTypeCd;
    }
    
    public void setOwnerTypeCd(String ownerTypeCd) {
        this.ownerTypeCd = ownerTypeCd;
    }

    
    @Column(name="owner_type_desc", nullable=false, length=50)
    public String getOwnerTypeDesc() {
        return this.ownerTypeDesc;
    }
    
    public void setOwnerTypeDesc(String ownerTypeDesc) {
        this.ownerTypeDesc = ownerTypeDesc;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


