package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayorType generated by hbm2java
 */
@Entity
@Table(name="payor_type"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PayorType  implements java.io.Serializable {


     private String payorTypeCd;
     private String payorTypeDesc;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public PayorType() {
    }

	
    public PayorType(String payorTypeCd, String payorTypeDesc) {
        this.payorTypeCd = payorTypeCd;
        this.payorTypeDesc = payorTypeDesc;
    }
    public PayorType(String payorTypeCd, String payorTypeDesc, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.payorTypeCd = payorTypeCd;
       this.payorTypeDesc = payorTypeDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="payor_type_cd", unique=true, nullable=false, length=50)
    public String getPayorTypeCd() {
        return this.payorTypeCd;
    }
    
    public void setPayorTypeCd(String payorTypeCd) {
        this.payorTypeCd = payorTypeCd;
    }

    
    @Column(name="payor_type_desc", nullable=false, length=50)
    public String getPayorTypeDesc() {
        return this.payorTypeDesc;
    }
    
    public void setPayorTypeDesc(String payorTypeDesc) {
        this.payorTypeDesc = payorTypeDesc;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


