package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayorCategory generated by hbm2java
 */
@Entity
@Table(name="payor_category"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PayorCategory  implements java.io.Serializable {


     private String payorCategoryCd;
     private String payorCategoryDesc;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public PayorCategory() {
    }

	
    public PayorCategory(String payorCategoryCd, String payorCategoryDesc) {
        this.payorCategoryCd = payorCategoryCd;
        this.payorCategoryDesc = payorCategoryDesc;
    }
    public PayorCategory(String payorCategoryCd, String payorCategoryDesc, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.payorCategoryCd = payorCategoryCd;
       this.payorCategoryDesc = payorCategoryDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="payor_category_cd", unique=true, nullable=false, length=50)
    public String getPayorCategoryCd() {
        return this.payorCategoryCd;
    }
    
    public void setPayorCategoryCd(String payorCategoryCd) {
        this.payorCategoryCd = payorCategoryCd;
    }

    
    @Column(name="payor_category_desc", nullable=false, length=50)
    public String getPayorCategoryDesc() {
        return this.payorCategoryDesc;
    }
    
    public void setPayorCategoryDesc(String payorCategoryDesc) {
        this.payorCategoryDesc = payorCategoryDesc;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


