package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfRole generated by hbm2java
 */
@Entity
@Table(name = "picf_role")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfRole implements java.io.Serializable {

	private BigDecimal id;
	private String roleName;
	private String roleDesc;
	private BigDecimal lastUpdatedUser;
	private Date lastUpdatedDate;
	private Byte isDeleted;
	private BigDecimal tenantId;
	private Set<PicfResourceRoles> picfResourceRoleses = new HashSet<PicfResourceRoles>(0);
	private Set<PicfRolePermissions> picfRolePermissionses = new HashSet<PicfRolePermissions>(0);

	public PicfRole() {
	}

	public PicfRole(String roleName) {
		this.roleName = roleName;
	}

	public PicfRole(String roleName, String roleDesc, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted,
			BigDecimal tenantId, Set<PicfResourceRoles> picfResourceRoleses,
			Set<PicfRolePermissions> picfRolePermissionses) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.lastUpdatedUser = lastUpdatedUser;
		this.lastUpdatedDate = lastUpdatedDate;
		this.isDeleted = isDeleted;
		this.tenantId = tenantId;
		this.picfResourceRoleses = picfResourceRoleses;
		this.picfRolePermissionses = picfRolePermissionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "role_name", nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", length = 500)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Column(name = "last_updated_user", scale = 0)
	public BigDecimal getLastUpdatedUser() {
		return this.lastUpdatedUser;
	}

	public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
		this.lastUpdatedUser = lastUpdatedUser;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "tenant_id", scale = 0)
	public BigDecimal getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(BigDecimal tenantId) {
		this.tenantId = tenantId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "picfRole")
	public Set<PicfResourceRoles> getPicfResourceRoleses() {
		return this.picfResourceRoleses;
	}

	public void setPicfResourceRoleses(Set<PicfResourceRoles> picfResourceRoleses) {
		this.picfResourceRoleses = picfResourceRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "picfRole")
	public Set<PicfRolePermissions> getPicfRolePermissionses() {
		return this.picfRolePermissionses;
	}

	public void setPicfRolePermissionses(Set<PicfRolePermissions> picfRolePermissionses) {
		this.picfRolePermissionses = picfRolePermissionses;
	}

}
