package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfMaskingTypes generated by hbm2java
 */
@Entity
@Table(name="picf_masking_types"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfMaskingTypes  implements java.io.Serializable {


     private BigDecimal id;
     private String fieldType;
     private String maskingTypeValue;
     private Date lastUpdatedDate;
     private BigDecimal lastUpdatedUser;
     private Byte isDeleted;
     private Set<PicfResponseOptions> picfResponseOptionses = new HashSet<PicfResponseOptions>(0);

    public PicfMaskingTypes() {
    }

    public PicfMaskingTypes(String fieldType, String maskingTypeValue, Date lastUpdatedDate, BigDecimal lastUpdatedUser, Byte isDeleted, Set<PicfResponseOptions> picfResponseOptionses) {
       this.fieldType = fieldType;
       this.maskingTypeValue = maskingTypeValue;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedUser = lastUpdatedUser;
       this.isDeleted = isDeleted;
       this.picfResponseOptionses = picfResponseOptionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="field_type", length=50)
    public String getFieldType() {
        return this.fieldType;
    }
    
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    
    @Column(name="masking_type_value", length=50)
    public String getMaskingTypeValue() {
        return this.maskingTypeValue;
    }
    
    public void setMaskingTypeValue(String maskingTypeValue) {
        this.maskingTypeValue = maskingTypeValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="picfMaskingTypes")
    public Set<PicfResponseOptions> getPicfResponseOptionses() {
        return this.picfResponseOptionses;
    }
    
    public void setPicfResponseOptionses(Set<PicfResponseOptions> picfResponseOptionses) {
        this.picfResponseOptionses = picfResponseOptionses;
    }




}


