package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfFormAudit generated by hbm2java
 */
@Entity
@Table(name="picf_form_audit"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfFormAudit  implements java.io.Serializable {


     private BigDecimal id;
     private PicfFormTemplate picfFormTemplate;
     private String resourceType;
     private BigDecimal resourceId;
     private String statusMsg;
     private String data;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;

    public PicfFormAudit() {
    }

    public PicfFormAudit(PicfFormTemplate picfFormTemplate, String resourceType, BigDecimal resourceId, String statusMsg, String data, BigDecimal lastUpdatedUser, Date lastUpdatedDate) {
       this.picfFormTemplate = picfFormTemplate;
       this.resourceType = resourceType;
       this.resourceId = resourceId;
       this.statusMsg = statusMsg;
       this.data = data;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="templateId")
    public PicfFormTemplate getPicfFormTemplate() {
        return this.picfFormTemplate;
    }
    
    public void setPicfFormTemplate(PicfFormTemplate picfFormTemplate) {
        this.picfFormTemplate = picfFormTemplate;
    }

    
    @Column(name="resourceType", length=50)
    public String getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    
    @Column(name="resourceId", scale=0)
    public BigDecimal getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(BigDecimal resourceId) {
        this.resourceId = resourceId;
    }

    
    @Column(name="status_msg", length=50)
    public String getStatusMsg() {
        return this.statusMsg;
    }
    
    public void setStatusMsg(String statusMsg) {
        this.statusMsg = statusMsg;
    }

    
    @Column(name="data", length=2048)
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }




}


