package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfColumnMetadata generated by hbm2java
 */
@Entity
@Table(name="picf_column_metadata"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfColumnMetadata  implements java.io.Serializable {


     private BigDecimal id;
     private PicfDashboard picfDashboard;
     private String name;
     private String displayName;
     private Integer location;
     private Integer width;
     private String format;
     private String type;
     private String filter;
     private Byte searchable;
     private Byte display;
     private Byte fetchable;
     private String alignment;
     private Byte sortable;
     private String defaultOrderBy;
     private Integer orderBySequence;
     private String action;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;
     private Byte isDeleted;

    public PicfColumnMetadata() {
    }

    public PicfColumnMetadata(PicfDashboard picfDashboard, String name, String displayName, Integer location, Integer width, String format, String type, String filter, Byte searchable, Byte display, Byte fetchable, String alignment, Byte sortable, String defaultOrderBy, Integer orderBySequence, String action, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted) {
       this.picfDashboard = picfDashboard;
       this.name = name;
       this.displayName = displayName;
       this.location = location;
       this.width = width;
       this.format = format;
       this.type = type;
       this.filter = filter;
       this.searchable = searchable;
       this.display = display;
       this.fetchable = fetchable;
       this.alignment = alignment;
       this.sortable = sortable;
       this.defaultOrderBy = defaultOrderBy;
       this.orderBySequence = orderBySequence;
       this.action = action;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dashboard_id")
    public PicfDashboard getPicfDashboard() {
        return this.picfDashboard;
    }
    
    public void setPicfDashboard(PicfDashboard picfDashboard) {
        this.picfDashboard = picfDashboard;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="displayName", length=45)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    
    @Column(name="location")
    public Integer getLocation() {
        return this.location;
    }
    
    public void setLocation(Integer location) {
        this.location = location;
    }

    
    @Column(name="width")
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }

    
    @Column(name="format", length=45)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="filter", length=45)
    public String getFilter() {
        return this.filter;
    }
    
    public void setFilter(String filter) {
        this.filter = filter;
    }

    
    @Column(name="searchable")
    public Byte getSearchable() {
        return this.searchable;
    }
    
    public void setSearchable(Byte searchable) {
        this.searchable = searchable;
    }

    
    @Column(name="display")
    public Byte getDisplay() {
        return this.display;
    }
    
    public void setDisplay(Byte display) {
        this.display = display;
    }

    
    @Column(name="fetchable")
    public Byte getFetchable() {
        return this.fetchable;
    }
    
    public void setFetchable(Byte fetchable) {
        this.fetchable = fetchable;
    }

    
    @Column(name="alignment", length=45)
    public String getAlignment() {
        return this.alignment;
    }
    
    public void setAlignment(String alignment) {
        this.alignment = alignment;
    }

    
    @Column(name="sortable")
    public Byte getSortable() {
        return this.sortable;
    }
    
    public void setSortable(Byte sortable) {
        this.sortable = sortable;
    }

    
    @Column(name="defaultOrderBy", length=10)
    public String getDefaultOrderBy() {
        return this.defaultOrderBy;
    }
    
    public void setDefaultOrderBy(String defaultOrderBy) {
        this.defaultOrderBy = defaultOrderBy;
    }

    
    @Column(name="orderBySequence")
    public Integer getOrderBySequence() {
        return this.orderBySequence;
    }
    
    public void setOrderBySequence(Integer orderBySequence) {
        this.orderBySequence = orderBySequence;
    }

    
    @Column(name="action", length=256)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


