package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfAttachment generated by hbm2java
 */
@Entity
@Table(name="picf_attachment"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfAttachment  implements java.io.Serializable {


     private BigDecimal id;
     private String attachmentName;
     private String documentId;
     private String pendingReqId;
     private String resourceType;
     private BigDecimal resourceId;
     private String uploadProgress;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;
     private Byte isDeleted;
     private Set<PicfFormAttachment> picfFormAttachments = new HashSet<PicfFormAttachment>(0);

    public PicfAttachment() {
    }

    public PicfAttachment(String attachmentName, String documentId, String pendingReqId, String resourceType, BigDecimal resourceId, String uploadProgress, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted, Set<PicfFormAttachment> picfFormAttachments) {
       this.attachmentName = attachmentName;
       this.documentId = documentId;
       this.pendingReqId = pendingReqId;
       this.resourceType = resourceType;
       this.resourceId = resourceId;
       this.uploadProgress = uploadProgress;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
       this.isDeleted = isDeleted;
       this.picfFormAttachments = picfFormAttachments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="attachmentName", length=200)
    public String getAttachmentName() {
        return this.attachmentName;
    }
    
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    
    @Column(name="documentId", length=200)
    public String getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    
    @Column(name="pendingReqId", length=200)
    public String getPendingReqId() {
        return this.pendingReqId;
    }
    
    public void setPendingReqId(String pendingReqId) {
        this.pendingReqId = pendingReqId;
    }

    
    @Column(name="resourceType", length=100)
    public String getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    
    @Column(name="resourceId", scale=0)
    public BigDecimal getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(BigDecimal resourceId) {
        this.resourceId = resourceId;
    }

    
    @Column(name="upload_progress")
    public String getUploadProgress() {
        return this.uploadProgress;
    }
    
    public void setUploadProgress(String uploadProgress) {
        this.uploadProgress = uploadProgress;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="picfAttachment")
    public Set<PicfFormAttachment> getPicfFormAttachments() {
        return this.picfFormAttachments;
    }
    
    public void setPicfFormAttachments(Set<PicfFormAttachment> picfFormAttachments) {
        this.picfFormAttachments = picfFormAttachments;
    }




}


