package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfResponseOptions generated by hbm2java
 */
@Entity
@Table(name="picf_response_options"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfResponseOptions  implements java.io.Serializable {


     private BigDecimal id;
     private PicfMaskingTypes picfMaskingTypes;
     private PicfQuestion picfQuestion;
     private Integer responseIndex;
     private String responseKey;
     private String responseValue;
     private BigDecimal reflexiveId;
     private String rendertypeId;
     private String datatype;
     private Integer maxlength;
     private Integer minlength;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;
     private Byte isDeleted;
     private Integer sortNum;
     private Date minDate;
     private Date maxDate;
     private Integer height;
     private Integer width;
     private String defaultValue;
     private String reflexiveShortName;

    public PicfResponseOptions() {
    }

	
    public PicfResponseOptions(PicfQuestion picfQuestion) {
        this.picfQuestion = picfQuestion;
    }
    public PicfResponseOptions(PicfMaskingTypes picfMaskingTypes, PicfQuestion picfQuestion, Integer responseIndex, String responseKey, String responseValue, BigDecimal reflexiveId, String rendertypeId, String datatype, Integer maxlength, Integer minlength, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted, Integer sortNum, Date minDate, Date maxDate, Integer height, Integer width, String defaultValue, String reflexiveShortName) {
       this.picfMaskingTypes = picfMaskingTypes;
       this.picfQuestion = picfQuestion;
       this.responseIndex = responseIndex;
       this.responseKey = responseKey;
       this.responseValue = responseValue;
       this.reflexiveId = reflexiveId;
       this.rendertypeId = rendertypeId;
       this.datatype = datatype;
       this.maxlength = maxlength;
       this.minlength = minlength;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
       this.isDeleted = isDeleted;
       this.sortNum = sortNum;
       this.minDate = minDate;
       this.maxDate = maxDate;
       this.height = height;
       this.width = width;
       this.defaultValue = defaultValue;
       this.reflexiveShortName = reflexiveShortName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="masktype_Id")
    public PicfMaskingTypes getPicfMaskingTypes() {
        return this.picfMaskingTypes;
    }
    
    public void setPicfMaskingTypes(PicfMaskingTypes picfMaskingTypes) {
        this.picfMaskingTypes = picfMaskingTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_question_Id", nullable=false)
    public PicfQuestion getPicfQuestion() {
        return this.picfQuestion;
    }
    
    public void setPicfQuestion(PicfQuestion picfQuestion) {
        this.picfQuestion = picfQuestion;
    }

    
    @Column(name="response_Index")
    public Integer getResponseIndex() {
        return this.responseIndex;
    }
    
    public void setResponseIndex(Integer responseIndex) {
        this.responseIndex = responseIndex;
    }

    
    @Column(name="response_Key", length=50)
    public String getResponseKey() {
        return this.responseKey;
    }
    
    public void setResponseKey(String responseKey) {
        this.responseKey = responseKey;
    }

    
    @Column(name="response_Value", length=500)
    public String getResponseValue() {
        return this.responseValue;
    }
    
    public void setResponseValue(String responseValue) {
        this.responseValue = responseValue;
    }

    
    @Column(name="reflexive_Id", scale=0)
    public BigDecimal getReflexiveId() {
        return this.reflexiveId;
    }
    
    public void setReflexiveId(BigDecimal reflexiveId) {
        this.reflexiveId = reflexiveId;
    }

    
    @Column(name="rendertype_Id", length=20)
    public String getRendertypeId() {
        return this.rendertypeId;
    }
    
    public void setRendertypeId(String rendertypeId) {
        this.rendertypeId = rendertypeId;
    }

    
    @Column(name="datatype", length=250)
    public String getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }

    
    @Column(name="maxlength")
    public Integer getMaxlength() {
        return this.maxlength;
    }
    
    public void setMaxlength(Integer maxlength) {
        this.maxlength = maxlength;
    }

    
    @Column(name="minlength")
    public Integer getMinlength() {
        return this.minlength;
    }
    
    public void setMinlength(Integer minlength) {
        this.minlength = minlength;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    
    @Column(name="sort_num")
    public Integer getSortNum() {
        return this.sortNum;
    }
    
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="min_Date", length=23)
    public Date getMinDate() {
        return this.minDate;
    }
    
    public void setMinDate(Date minDate) {
        this.minDate = minDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="max_Date", length=23)
    public Date getMaxDate() {
        return this.maxDate;
    }
    
    public void setMaxDate(Date maxDate) {
        this.maxDate = maxDate;
    }

    
    @Column(name="height")
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }

    
    @Column(name="width")
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }

    
    @Column(name="default_Value", length=500)
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    
    @Column(name="reflexive_short_name", length=50)
    public String getReflexiveShortName() {
        return this.reflexiveShortName;
    }
    
    public void setReflexiveShortName(String reflexiveShortName) {
        this.reflexiveShortName = reflexiveShortName;
    }




}


