package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfAttributeSet generated by hbm2java
 */
@Entity
@Table(name="picf_attribute_set"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfAttributeSet  implements java.io.Serializable {


     private BigDecimal id;
     private String attrSetname;
     private String resourceDn;
     private BigDecimal tenantId;
     private String attrSetDesc;
     private Character isDraft;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;
     private Byte isDeleted;
     private Set<PicfFormTemplate> picfFormTemplates = new HashSet<PicfFormTemplate>(0);
     private Set<PicfAttribute> picfAttributes = new HashSet<PicfAttribute>(0);
     private Set<PicfAsEntityMapping> picfAsEntityMappings = new HashSet<PicfAsEntityMapping>(0);

    public PicfAttributeSet() {
    }

    public PicfAttributeSet(String attrSetname, String resourceDn, BigDecimal tenantId, String attrSetDesc, Character isDraft, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted, Set<PicfFormTemplate> picfFormTemplates, Set<PicfAttribute> picfAttributes, Set<PicfAsEntityMapping> picfAsEntityMappings) {
       this.attrSetname = attrSetname;
       this.resourceDn = resourceDn;
       this.tenantId = tenantId;
       this.attrSetDesc = attrSetDesc;
       this.isDraft = isDraft;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
       this.isDeleted = isDeleted;
       this.picfFormTemplates = picfFormTemplates;
       this.picfAttributes = picfAttributes;
       this.picfAsEntityMappings = picfAsEntityMappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="attrSetname", length=250)
    public String getAttrSetname() {
        return this.attrSetname;
    }
    
    public void setAttrSetname(String attrSetname) {
        this.attrSetname = attrSetname;
    }

    
    @Column(name="resource_dn", length=150)
    public String getResourceDn() {
        return this.resourceDn;
    }
    
    public void setResourceDn(String resourceDn) {
        this.resourceDn = resourceDn;
    }

    
    @Column(name="tenant_id", scale=0)
    public BigDecimal getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(BigDecimal tenantId) {
        this.tenantId = tenantId;
    }

    
    @Column(name="attrSetDesc", length=250)
    public String getAttrSetDesc() {
        return this.attrSetDesc;
    }
    
    public void setAttrSetDesc(String attrSetDesc) {
        this.attrSetDesc = attrSetDesc;
    }

    
    @Column(name="is_draft", length=1)
    public Character getIsDraft() {
        return this.isDraft;
    }
    
    public void setIsDraft(Character isDraft) {
        this.isDraft = isDraft;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="picfAttributeSet")
    public Set<PicfFormTemplate> getPicfFormTemplates() {
        return this.picfFormTemplates;
    }
    
    public void setPicfFormTemplates(Set<PicfFormTemplate> picfFormTemplates) {
        this.picfFormTemplates = picfFormTemplates;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="picfAttributeSet")
    public Set<PicfAttribute> getPicfAttributes() {
        return this.picfAttributes;
    }
    
    public void setPicfAttributes(Set<PicfAttribute> picfAttributes) {
        this.picfAttributes = picfAttributes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="picfAttributeSet")
    public Set<PicfAsEntityMapping> getPicfAsEntityMappings() {
        return this.picfAsEntityMappings;
    }
    
    public void setPicfAsEntityMappings(Set<PicfAsEntityMapping> picfAsEntityMappings) {
        this.picfAsEntityMappings = picfAsEntityMappings;
    }




}


