package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PicfResourceActions generated by hbm2java
 */
@Entity
@Table(name="picf_resource_actions"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfResourceActions  implements java.io.Serializable {


     private BigDecimal id;
     private PicfOperations picfOperations;
     private String entityType;

    public PicfResourceActions() {
    }

	
    public PicfResourceActions(PicfOperations picfOperations) {
        this.picfOperations = picfOperations;
    }
    public PicfResourceActions(PicfOperations picfOperations, String entityType) {
       this.picfOperations = picfOperations;
       this.entityType = entityType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operation_id", nullable=false)
    public PicfOperations getPicfOperations() {
        return this.picfOperations;
    }
    
    public void setPicfOperations(PicfOperations picfOperations) {
        this.picfOperations = picfOperations;
    }

    
    @Column(name="entity_type", length=150)
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }




}


