package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PicfMetricsReqTime generated by hbm2java
 */
@Entity
@Table(name="picf_metrics_req_time"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfMetricsReqTime  implements java.io.Serializable {


     private String tid;
     private BigDecimal id;
     private String userId;
     private String module;
     private BigDecimal starttime;
     private BigDecimal endtime;
     private BigDecimal reqtime;

    public PicfMetricsReqTime() {
    }

	
    public PicfMetricsReqTime(String tid, BigDecimal id) {
        this.tid = tid;
        this.id = id;
    }
    public PicfMetricsReqTime(String tid, BigDecimal id, String userId, String module, BigDecimal starttime, BigDecimal endtime, BigDecimal reqtime) {
       this.tid = tid;
       this.id = id;
       this.userId = userId;
       this.module = module;
       this.starttime = starttime;
       this.endtime = endtime;
       this.reqtime = reqtime;
    }
   
     @Id 

    
    @Column(name="tid", unique=true, nullable=false, length=45)
    public String getTid() {
        return this.tid;
    }
    
    public void setTid(String tid) {
        this.tid = tid;
    }

    
    @Column(name="id", nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="user_id", length=45)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="module", length=45)
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }

    
    @Column(name="starttime", scale=0)
    public BigDecimal getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(BigDecimal starttime) {
        this.starttime = starttime;
    }

    
    @Column(name="endtime", scale=0)
    public BigDecimal getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(BigDecimal endtime) {
        this.endtime = endtime;
    }

    
    @Column(name="reqtime", scale=0)
    public BigDecimal getReqtime() {
        return this.reqtime;
    }
    
    public void setReqtime(BigDecimal reqtime) {
        this.reqtime = reqtime;
    }




}


