package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfFormCntxtMapping generated by hbm2java
 */
@Entity
@Table(name="picf_form_cntxt_mapping"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfFormCntxtMapping  implements java.io.Serializable {


     private BigDecimal id;
     private PicfFormCntxtDefinition picfFormCntxtDefinition;
     private PicfFormTemplate picfFormTemplate;
     private Byte useInCntxt;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;
     private BigDecimal tenantId;

    public PicfFormCntxtMapping() {
    }

    public PicfFormCntxtMapping(PicfFormCntxtDefinition picfFormCntxtDefinition, PicfFormTemplate picfFormTemplate, Byte useInCntxt, BigDecimal lastUpdatedUser, Date lastUpdatedDate, BigDecimal tenantId) {
       this.picfFormCntxtDefinition = picfFormCntxtDefinition;
       this.picfFormTemplate = picfFormTemplate;
       this.useInCntxt = useInCntxt;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
       this.tenantId = tenantId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="form_cntxt_id")
    public PicfFormCntxtDefinition getPicfFormCntxtDefinition() {
        return this.picfFormCntxtDefinition;
    }
    
    public void setPicfFormCntxtDefinition(PicfFormCntxtDefinition picfFormCntxtDefinition) {
        this.picfFormCntxtDefinition = picfFormCntxtDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="form_id")
    public PicfFormTemplate getPicfFormTemplate() {
        return this.picfFormTemplate;
    }
    
    public void setPicfFormTemplate(PicfFormTemplate picfFormTemplate) {
        this.picfFormTemplate = picfFormTemplate;
    }

    
    @Column(name="use_in_cntxt")
    public Byte getUseInCntxt() {
        return this.useInCntxt;
    }
    
    public void setUseInCntxt(Byte useInCntxt) {
        this.useInCntxt = useInCntxt;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="tenant_id", scale=0)
    public BigDecimal getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(BigDecimal tenantId) {
        this.tenantId = tenantId;
    }




}


