package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfTheme generated by hbm2java
 */
@Entity
@Table(name="picf_theme"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfTheme  implements java.io.Serializable {


     private BigDecimal id;
     private String themeName;
     private String themeIdName;
     private String filePath;
     private Date lastUpdatedDate;
     private BigDecimal lastUpdatedUser;
     private Byte isDeleted;

    public PicfTheme() {
    }

	
    public PicfTheme(String themeName, String themeIdName, String filePath) {
        this.themeName = themeName;
        this.themeIdName = themeIdName;
        this.filePath = filePath;
    }
    public PicfTheme(String themeName, String themeIdName, String filePath, Date lastUpdatedDate, BigDecimal lastUpdatedUser, Byte isDeleted) {
       this.themeName = themeName;
       this.themeIdName = themeIdName;
       this.filePath = filePath;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedUser = lastUpdatedUser;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="theme_name", nullable=false, length=100)
    public String getThemeName() {
        return this.themeName;
    }
    
    public void setThemeName(String themeName) {
        this.themeName = themeName;
    }

    
    @Column(name="theme_id_name", nullable=false, length=100)
    public String getThemeIdName() {
        return this.themeIdName;
    }
    
    public void setThemeIdName(String themeIdName) {
        this.themeIdName = themeIdName;
    }

    
    @Column(name="file_path", nullable=false, length=200)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


