package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfQuestionNameSpace generated by hbm2java
 */
@Entity
@Table(name="picf_question_nameSpace"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfQuestionNameSpace  implements java.io.Serializable {


     private BigDecimal id;
     private String nameSpace;
     private Date lastUpdatedDate;
     private BigDecimal lastUpdatedUser;
     private Byte isDeleted;

    public PicfQuestionNameSpace() {
    }

    public PicfQuestionNameSpace(String nameSpace, Date lastUpdatedDate, BigDecimal lastUpdatedUser, Byte isDeleted) {
       this.nameSpace = nameSpace;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedUser = lastUpdatedUser;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="nameSpace", length=1000)
    public String getNameSpace() {
        return this.nameSpace;
    }
    
    public void setNameSpace(String nameSpace) {
        this.nameSpace = nameSpace;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


