package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfTenantTheme generated by hbm2java
 */
@Entity
@Table(name = "picf_tenant_theme")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfTenantTheme implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal tenantId;
	private BigDecimal themeId;
	private Byte isDefault;
	private Date lastUpdateDate;

	public PicfTenantTheme() {
	}

	public PicfTenantTheme(BigDecimal tenantId, BigDecimal themeId) {
		this.tenantId = tenantId;
		this.themeId = themeId;
	}

	public PicfTenantTheme(BigDecimal tenantId, BigDecimal themeId, Byte isDefault, Date lastUpdateDate) {
		this.tenantId = tenantId;
		this.themeId = themeId;
		this.isDefault = isDefault;
		this.lastUpdateDate = lastUpdateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "tenant_id", nullable = false, scale = 0)
	public BigDecimal getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(BigDecimal tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "theme_id", nullable = false, scale = 0)
	public BigDecimal getThemeId() {
		return this.themeId;
	}

	public void setThemeId(BigDecimal themeId) {
		this.themeId = themeId;
	}

	@Column(name = "isDefault")
	public Byte getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Byte isDefault) {
		this.isDefault = isDefault;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_date", length = 23)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
