package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfEventTypes generated by hbm2java
 */
@Entity
@Table(name = "picf_event_types")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfEventTypes implements java.io.Serializable {

	private BigDecimal id;
	private PicfQuestion picfQuestion;
	private String eventTypeCode;
	private String eventTypeValue;
	private Date lastUpdatedDate;
	private BigDecimal lastUpdatedUser;
	private Byte isDeleted;

	public PicfEventTypes() {
	}

	public PicfEventTypes(PicfQuestion picfQuestion) {
		this.picfQuestion = picfQuestion;
	}

	public PicfEventTypes(PicfQuestion picfQuestion, String eventTypeCode, String eventTypeValue, Date lastUpdatedDate,
			BigDecimal lastUpdatedUser, Byte isDeleted) {
		this.picfQuestion = picfQuestion;
		this.eventTypeCode = eventTypeCode;
		this.eventTypeValue = eventTypeValue;
		this.lastUpdatedDate = lastUpdatedDate;
		this.lastUpdatedUser = lastUpdatedUser;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_Id", nullable = false)
	public PicfQuestion getPicfQuestion() {
		return this.picfQuestion;
	}

	public void setPicfQuestion(PicfQuestion picfQuestion) {
		this.picfQuestion = picfQuestion;
	}

	@Column(name = "event_type_code", length = 45)
	public String getEventTypeCode() {
		return this.eventTypeCode;
	}

	public void setEventTypeCode(String eventTypeCode) {
		this.eventTypeCode = eventTypeCode;
	}

	@Column(name = "event_type_value", length = 45)
	public String getEventTypeValue() {
		return this.eventTypeValue;
	}

	public void setEventTypeValue(String eventTypeValue) {
		this.eventTypeValue = eventTypeValue;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "last_updated_user", scale = 0)
	public BigDecimal getLastUpdatedUser() {
		return this.lastUpdatedUser;
	}

	public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
		this.lastUpdatedUser = lastUpdatedUser;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

}
