package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfTenant generated by hbm2java
 */
@Entity
@Table(name = "picf_tenant")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfTenant implements java.io.Serializable {

	private BigDecimal tenantId;
	private String tenant;
	private BigDecimal prodId;
	private String prodVersion;
	private String prodRelease;
	private BigDecimal lastUpdatedUser;
	private Date lastUpdatedDate;
	private Byte isDeleted;

	public PicfTenant() {
	}

	public PicfTenant(String tenant, BigDecimal prodId, String prodVersion, String prodRelease) {
		this.tenant = tenant;
		this.prodId = prodId;
		this.prodVersion = prodVersion;
		this.prodRelease = prodRelease;
	}

	public PicfTenant(String tenant, BigDecimal prodId, String prodVersion, String prodRelease,
			BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted) {
		this.tenant = tenant;
		this.prodId = prodId;
		this.prodVersion = prodVersion;
		this.prodRelease = prodRelease;
		this.lastUpdatedUser = lastUpdatedUser;
		this.lastUpdatedDate = lastUpdatedDate;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tenant_id", unique = true, nullable = false, scale = 0)
	public BigDecimal getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(BigDecimal tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "tenant", nullable = false, length = 45)
	public String getTenant() {
		return this.tenant;
	}

	public void setTenant(String tenant) {
		this.tenant = tenant;
	}

	@Column(name = "prod_id", nullable = false, scale = 0)
	public BigDecimal getProdId() {
		return this.prodId;
	}

	public void setProdId(BigDecimal prodId) {
		this.prodId = prodId;
	}

	@Column(name = "prod_version", nullable = false, length = 45)
	public String getProdVersion() {
		return this.prodVersion;
	}

	public void setProdVersion(String prodVersion) {
		this.prodVersion = prodVersion;
	}

	@Column(name = "prod_release", nullable = false, length = 45)
	public String getProdRelease() {
		return this.prodRelease;
	}

	public void setProdRelease(String prodRelease) {
		this.prodRelease = prodRelease;
	}

	@Column(name = "last_updated_user", scale = 0)
	public BigDecimal getLastUpdatedUser() {
		return this.lastUpdatedUser;
	}

	public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
		this.lastUpdatedUser = lastUpdatedUser;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

}
