package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfAttributeValue generated by hbm2java
 */
@Entity
@Table(name = "picf_attribute_value")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfAttributeValue implements java.io.Serializable {

	private BigDecimal attrValId;
	private PicfAttribute picfAttribute;
	private String attrValue;
	private String resourceType;
	private BigDecimal resourceId;
	private BigDecimal tenantId;
	private Byte isDeleted;
	private BigDecimal lastUpdatedUser;
	private Date lastUpdatedDate;

	public PicfAttributeValue() {
	}

	public PicfAttributeValue(PicfAttribute picfAttribute, String attrValue, String resourceType, BigDecimal resourceId,
			BigDecimal tenantId, Byte isDeleted, BigDecimal lastUpdatedUser, Date lastUpdatedDate) {
		this.picfAttribute = picfAttribute;
		this.attrValue = attrValue;
		this.resourceType = resourceType;
		this.resourceId = resourceId;
		this.tenantId = tenantId;
		this.isDeleted = isDeleted;
		this.lastUpdatedUser = lastUpdatedUser;
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attrValId", unique = true, nullable = false, scale = 0)
	public BigDecimal getAttrValId() {
		return this.attrValId;
	}

	public void setAttrValId(BigDecimal attrValId) {
		this.attrValId = attrValId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attrId")
	public PicfAttribute getPicfAttribute() {
		return this.picfAttribute;
	}

	public void setPicfAttribute(PicfAttribute picfAttribute) {
		this.picfAttribute = picfAttribute;
	}

	@Column(name = "attrValue", length = 150)
	public String getAttrValue() {
		return this.attrValue;
	}

	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}

	@Column(name = "resource_type", length = 50)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "resource_id", scale = 0)
	public BigDecimal getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(BigDecimal resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "tenant_id", scale = 0)
	public BigDecimal getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(BigDecimal tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "last_updated_user", scale = 0)
	public BigDecimal getLastUpdatedUser() {
		return this.lastUpdatedUser;
	}

	public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
		this.lastUpdatedUser = lastUpdatedUser;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

}
