package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfQueryLookup generated by hbm2java
 */
@Entity
@Table(name="picf_query_lookup"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfQueryLookup  implements java.io.Serializable {


     private BigDecimal id;
     private PicfQueryDetails picfQueryDetails;
     private String workspaceId;
     private Integer viewId;
     private BigDecimal resourceId;
     private String entity;
     private String gridId;
     private Date lastUpdatedDate;
     private BigDecimal lastUpdatedUser;
     private Byte isDeleted;

    public PicfQueryLookup() {
    }

    public PicfQueryLookup(PicfQueryDetails picfQueryDetails, String workspaceId, Integer viewId, BigDecimal resourceId, String entity, String gridId, Date lastUpdatedDate, BigDecimal lastUpdatedUser, Byte isDeleted) {
       this.picfQueryDetails = picfQueryDetails;
       this.workspaceId = workspaceId;
       this.viewId = viewId;
       this.resourceId = resourceId;
       this.entity = entity;
       this.gridId = gridId;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedUser = lastUpdatedUser;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="query_id")
    public PicfQueryDetails getPicfQueryDetails() {
        return this.picfQueryDetails;
    }
    
    public void setPicfQueryDetails(PicfQueryDetails picfQueryDetails) {
        this.picfQueryDetails = picfQueryDetails;
    }

    
    @Column(name="workspace_id")
    public String getWorkspaceId() {
        return this.workspaceId;
    }
    
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    
    @Column(name="view_id")
    public Integer getViewId() {
        return this.viewId;
    }
    
    public void setViewId(Integer viewId) {
        this.viewId = viewId;
    }

    
    @Column(name="resource_id", scale=0)
    public BigDecimal getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(BigDecimal resourceId) {
        this.resourceId = resourceId;
    }

    
    @Column(name="entity", length=256)
    public String getEntity() {
        return this.entity;
    }
    
    public void setEntity(String entity) {
        this.entity = entity;
    }

    
    @Column(name="grid_id", length=128)
    public String getGridId() {
        return this.gridId;
    }
    
    public void setGridId(String gridId) {
        this.gridId = gridId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


