package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfAudit generated by hbm2java
 */
@Entity
@Table(name = "picf_audit")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfAudit implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal changedEntityId;
	private String changedEntity;
	private String changedField;
	private String changeReason;
	private String changeEventCd;
	private String changeNewRecordValue;
	private String changeOldRecordValue;
	private String remarks;
	private String transactionId;
	private Integer auditType;
	private BigDecimal changeUsrId;
	private Date changeDtm;

	public PicfAudit() {
	}

	public PicfAudit(BigDecimal changedEntityId) {
		this.changedEntityId = changedEntityId;
	}

	public PicfAudit(BigDecimal changedEntityId, String changedEntity, String changedField, String changeReason,
			String changeEventCd, String changeNewRecordValue, String changeOldRecordValue, String remarks,
			String transactionId, Integer auditType, BigDecimal changeUsrId, Date changeDtm) {
		this.changedEntityId = changedEntityId;
		this.changedEntity = changedEntity;
		this.changedField = changedField;
		this.changeReason = changeReason;
		this.changeEventCd = changeEventCd;
		this.changeNewRecordValue = changeNewRecordValue;
		this.changeOldRecordValue = changeOldRecordValue;
		this.remarks = remarks;
		this.transactionId = transactionId;
		this.auditType = auditType;
		this.changeUsrId = changeUsrId;
		this.changeDtm = changeDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "changed_entity_id", nullable = false, scale = 0)
	public BigDecimal getChangedEntityId() {
		return this.changedEntityId;
	}

	public void setChangedEntityId(BigDecimal changedEntityId) {
		this.changedEntityId = changedEntityId;
	}

	@Column(name = "changed_entity", length = 500)
	public String getChangedEntity() {
		return this.changedEntity;
	}

	public void setChangedEntity(String changedEntity) {
		this.changedEntity = changedEntity;
	}

	@Column(name = "changed_field", length = 500)
	public String getChangedField() {
		return this.changedField;
	}

	public void setChangedField(String changedField) {
		this.changedField = changedField;
	}

	@Column(name = "change_reason", length = 500)
	public String getChangeReason() {
		return this.changeReason;
	}

	public void setChangeReason(String changeReason) {
		this.changeReason = changeReason;
	}

	@Column(name = "change_event_cd", length = 45)
	public String getChangeEventCd() {
		return this.changeEventCd;
	}

	public void setChangeEventCd(String changeEventCd) {
		this.changeEventCd = changeEventCd;
	}

	@Column(name = "change_new_record_value", length = 500)
	public String getChangeNewRecordValue() {
		return this.changeNewRecordValue;
	}

	public void setChangeNewRecordValue(String changeNewRecordValue) {
		this.changeNewRecordValue = changeNewRecordValue;
	}

	@Column(name = "change_old_record_value", length = 500)
	public String getChangeOldRecordValue() {
		return this.changeOldRecordValue;
	}

	public void setChangeOldRecordValue(String changeOldRecordValue) {
		this.changeOldRecordValue = changeOldRecordValue;
	}

	@Column(name = "remarks", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "transaction_id", length = 50)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "audit_type")
	public Integer getAuditType() {
		return this.auditType;
	}

	public void setAuditType(Integer auditType) {
		this.auditType = auditType;
	}

	@Column(name = "change_usr_id", scale = 0)
	public BigDecimal getChangeUsrId() {
		return this.changeUsrId;
	}

	public void setChangeUsrId(BigDecimal changeUsrId) {
		this.changeUsrId = changeUsrId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_dtm", length = 23)
	public Date getChangeDtm() {
		return this.changeDtm;
	}

	public void setChangeDtm(Date changeDtm) {
		this.changeDtm = changeDtm;
	}

}
