package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfCommunication generated by hbm2java
 */
@Entity
@Table(name = "picf_communication")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfCommunication implements java.io.Serializable {

	private BigDecimal id;
	private PicfCommunicationTemplate picfCommunicationTemplate;
	private String communicationType;
	private String fromRecipient;
	private String toRecipients;
	private String ccRecipients;
	private String bccRecipients;
	private String subject;
	private String body;
	private String priority;
	private String status;
	private Date sentDtm;
	private String resourceType;
	private BigDecimal resourceId;
	private BigDecimal lastUpdatedUser;
	private Date lastUpdatedDate;
	private Byte isDeleted;

	public PicfCommunication() {
	}

	public PicfCommunication(String communicationType, String status, String resourceType, BigDecimal resourceId) {
		this.communicationType = communicationType;
		this.status = status;
		this.resourceType = resourceType;
		this.resourceId = resourceId;
	}

	public PicfCommunication(PicfCommunicationTemplate picfCommunicationTemplate, String communicationType,
			String fromRecipient, String toRecipients, String ccRecipients, String bccRecipients, String subject,
			String body, String priority, String status, Date sentDtm, String resourceType, BigDecimal resourceId,
			BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted) {
		this.picfCommunicationTemplate = picfCommunicationTemplate;
		this.communicationType = communicationType;
		this.fromRecipient = fromRecipient;
		this.toRecipients = toRecipients;
		this.ccRecipients = ccRecipients;
		this.bccRecipients = bccRecipients;
		this.subject = subject;
		this.body = body;
		this.priority = priority;
		this.status = status;
		this.sentDtm = sentDtm;
		this.resourceType = resourceType;
		this.resourceId = resourceId;
		this.lastUpdatedUser = lastUpdatedUser;
		this.lastUpdatedDate = lastUpdatedDate;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "templateId")
	public PicfCommunicationTemplate getPicfCommunicationTemplate() {
		return this.picfCommunicationTemplate;
	}

	public void setPicfCommunicationTemplate(PicfCommunicationTemplate picfCommunicationTemplate) {
		this.picfCommunicationTemplate = picfCommunicationTemplate;
	}

	@Column(name = "communicationType", nullable = false, length = 5)
	public String getCommunicationType() {
		return this.communicationType;
	}

	public void setCommunicationType(String communicationType) {
		this.communicationType = communicationType;
	}

	@Column(name = "fromRecipient", length = 100)
	public String getFromRecipient() {
		return this.fromRecipient;
	}

	public void setFromRecipient(String fromRecipient) {
		this.fromRecipient = fromRecipient;
	}

	@Column(name = "toRecipients", length = 500)
	public String getToRecipients() {
		return this.toRecipients;
	}

	public void setToRecipients(String toRecipients) {
		this.toRecipients = toRecipients;
	}

	@Column(name = "ccRecipients", length = 500)
	public String getCcRecipients() {
		return this.ccRecipients;
	}

	public void setCcRecipients(String ccRecipients) {
		this.ccRecipients = ccRecipients;
	}

	@Column(name = "bccRecipients", length = 500)
	public String getBccRecipients() {
		return this.bccRecipients;
	}

	public void setBccRecipients(String bccRecipients) {
		this.bccRecipients = bccRecipients;
	}

	@Column(name = "subject", length = 500)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "body", length = 5000)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "priority", length = 10)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent_dtm", length = 23)
	public Date getSentDtm() {
		return this.sentDtm;
	}

	public void setSentDtm(Date sentDtm) {
		this.sentDtm = sentDtm;
	}

	@Column(name = "resourceType", nullable = false, length = 50)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "resourceId", nullable = false, scale = 0)
	public BigDecimal getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(BigDecimal resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "last_updated_user", scale = 0)
	public BigDecimal getLastUpdatedUser() {
		return this.lastUpdatedUser;
	}

	public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
		this.lastUpdatedUser = lastUpdatedUser;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

}
