package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PicfEntityDefinition generated by hbm2java
 */
@Entity
@Table(name = "picf_entity_definition")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PicfEntityDefinition implements java.io.Serializable {

	private BigDecimal id;
	private String entityName;
	private String tableName;
	private String displayName;
	private String entityType;
	private String classAnnotations;
	private Character softDelReq;
	private String description;
	private String attributeMetadata;
	private Character isDraft;
	private BigDecimal lastUpdatedUser;
	private Date lastUpdatedDate;
	private Byte isDeleted;

	public PicfEntityDefinition() {
	}

	public PicfEntityDefinition(String entityName, String tableName, String displayName) {
		this.entityName = entityName;
		this.tableName = tableName;
		this.displayName = displayName;
	}

	public PicfEntityDefinition(String entityName, String tableName, String displayName, String entityType,
			String classAnnotations, Character softDelReq, String description, String attributeMetadata,
			Character isDraft, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Byte isDeleted) {
		this.entityName = entityName;
		this.tableName = tableName;
		this.displayName = displayName;
		this.entityType = entityType;
		this.classAnnotations = classAnnotations;
		this.softDelReq = softDelReq;
		this.description = description;
		this.attributeMetadata = attributeMetadata;
		this.isDraft = isDraft;
		this.lastUpdatedUser = lastUpdatedUser;
		this.lastUpdatedDate = lastUpdatedDate;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "entity_name", nullable = false, length = 45)
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "table_name", nullable = false, length = 35)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "display_name", nullable = false, length = 45)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "entity_type", length = 45)
	public String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	@Column(name = "class_annotations", length = 250)
	public String getClassAnnotations() {
		return this.classAnnotations;
	}

	public void setClassAnnotations(String classAnnotations) {
		this.classAnnotations = classAnnotations;
	}

	@Column(name = "softDelReq", length = 1)
	public Character getSoftDelReq() {
		return this.softDelReq;
	}

	public void setSoftDelReq(Character softDelReq) {
		this.softDelReq = softDelReq;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "attribute_metadata", length = 8000)
	public String getAttributeMetadata() {
		return this.attributeMetadata;
	}

	public void setAttributeMetadata(String attributeMetadata) {
		this.attributeMetadata = attributeMetadata;
	}

	@Column(name = "is_draft", length = 1)
	public Character getIsDraft() {
		return this.isDraft;
	}

	public void setIsDraft(Character isDraft) {
		this.isDraft = isDraft;
	}

	@Column(name = "last_updated_user", scale = 0)
	public BigDecimal getLastUpdatedUser() {
		return this.lastUpdatedUser;
	}

	public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
		this.lastUpdatedUser = lastUpdatedUser;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

}
