package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PicfCommunicationTemplate generated by hbm2java
 */
@Entity
@Table(name="picf_communication_template"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class PicfCommunicationTemplate  implements java.io.Serializable {


     private BigDecimal id;
     private String templateName;
     private String description;
     private String templateType;
     private String fromRecipient;
     private String toRecipients;
     private String ccRecipients;
     private String bccRecipients;
     private String subject;
     private String body;
     private String priority;
     private char isDraft;
     private Byte isDeleted;
     private BigDecimal lastUpdatedUser;
     private Date lastUpdatedDate;
     private Set<PicfCommunication> picfCommunications = new HashSet<PicfCommunication>(0);
     private Set<PicfFormTemplate> picfFormTemplates = new HashSet<PicfFormTemplate>(0);

    public PicfCommunicationTemplate() {
    }

	
    public PicfCommunicationTemplate(String templateName, String templateType, char isDraft) {
        this.templateName = templateName;
        this.templateType = templateType;
        this.isDraft = isDraft;
    }
    public PicfCommunicationTemplate(String templateName, String description, String templateType, String fromRecipient, String toRecipients, String ccRecipients, String bccRecipients, String subject, String body, String priority, char isDraft, Byte isDeleted, BigDecimal lastUpdatedUser, Date lastUpdatedDate, Set<PicfCommunication> picfCommunications, Set<PicfFormTemplate> picfFormTemplates) {
       this.templateName = templateName;
       this.description = description;
       this.templateType = templateType;
       this.fromRecipient = fromRecipient;
       this.toRecipients = toRecipients;
       this.ccRecipients = ccRecipients;
       this.bccRecipients = bccRecipients;
       this.subject = subject;
       this.body = body;
       this.priority = priority;
       this.isDraft = isDraft;
       this.isDeleted = isDeleted;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedDate = lastUpdatedDate;
       this.picfCommunications = picfCommunications;
       this.picfFormTemplates = picfFormTemplates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="templateName", nullable=false, length=30)
    public String getTemplateName() {
        return this.templateName;
    }
    
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    
    @Column(name="description", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="templateType", nullable=false, length=5)
    public String getTemplateType() {
        return this.templateType;
    }
    
    public void setTemplateType(String templateType) {
        this.templateType = templateType;
    }

    
    @Column(name="fromRecipient", length=100)
    public String getFromRecipient() {
        return this.fromRecipient;
    }
    
    public void setFromRecipient(String fromRecipient) {
        this.fromRecipient = fromRecipient;
    }

    
    @Column(name="toRecipients", length=500)
    public String getToRecipients() {
        return this.toRecipients;
    }
    
    public void setToRecipients(String toRecipients) {
        this.toRecipients = toRecipients;
    }

    
    @Column(name="ccRecipients", length=500)
    public String getCcRecipients() {
        return this.ccRecipients;
    }
    
    public void setCcRecipients(String ccRecipients) {
        this.ccRecipients = ccRecipients;
    }

    
    @Column(name="bccRecipients", length=500)
    public String getBccRecipients() {
        return this.bccRecipients;
    }
    
    public void setBccRecipients(String bccRecipients) {
        this.bccRecipients = bccRecipients;
    }

    
    @Column(name="subject", length=500)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="body", length=5000)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="priority", length=10)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="isDraft", nullable=false, length=1)
    public char getIsDraft() {
        return this.isDraft;
    }
    
    public void setIsDraft(char isDraft) {
        this.isDraft = isDraft;
    }

    
    @Column(name="is_deleted")
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    
    @Column(name="last_updated_user", scale=0)
    public BigDecimal getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(BigDecimal lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=23)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="picfCommunicationTemplate")
    public Set<PicfCommunication> getPicfCommunications() {
        return this.picfCommunications;
    }
    
    public void setPicfCommunications(Set<PicfCommunication> picfCommunications) {
        this.picfCommunications = picfCommunications;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="picf_communication_form", schema="dbo", catalog="life_eapp", joinColumns = { 
        @JoinColumn(name="templateId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="formId", nullable=false, updatable=false) })
    public Set<PicfFormTemplate> getPicfFormTemplates() {
        return this.picfFormTemplates;
    }
    
    public void setPicfFormTemplates(Set<PicfFormTemplate> picfFormTemplates) {
        this.picfFormTemplates = picfFormTemplates;
    }




}


