package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PlanCoverage generated by hbm2java
 */
@Entity
@Table(name = "plan_coverage")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlanCoverage implements java.io.Serializable {

	private int planCoverageId;
	private Integer planId;
	private int pcovSeqNum;
	private int covPlanCd;
	private int parntPlanCd;
	private Integer parntPcovSeqNum;
	private Character pcovHasDepInd;
	private Character isDeletedInd;
	private Date lstUpdtDtm;
	private String lstUpdtUserid;
	private Integer prodId;

	public PlanCoverage() {
	}

	public PlanCoverage(int planCoverageId, int pcovSeqNum, int covPlanCd, int parntPlanCd) {
		this.planCoverageId = planCoverageId;
		this.pcovSeqNum = pcovSeqNum;
		this.covPlanCd = covPlanCd;
		this.parntPlanCd = parntPlanCd;
	}

	public PlanCoverage(int planCoverageId, Integer planId, int pcovSeqNum, int covPlanCd, int parntPlanCd,
			Integer parntPcovSeqNum, Character pcovHasDepInd, Character isDeletedInd, Date lstUpdtDtm,
			String lstUpdtUserid, Integer prodId) {
		this.planCoverageId = planCoverageId;
		this.planId = planId;
		this.pcovSeqNum = pcovSeqNum;
		this.covPlanCd = covPlanCd;
		this.parntPlanCd = parntPlanCd;
		this.parntPcovSeqNum = parntPcovSeqNum;
		this.pcovHasDepInd = pcovHasDepInd;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
		this.lstUpdtUserid = lstUpdtUserid;
		this.prodId = prodId;
	}

	@Id

	@Column(name = "plan_coverage_id", unique = true, nullable = false)
	public int getPlanCoverageId() {
		return this.planCoverageId;
	}

	public void setPlanCoverageId(int planCoverageId) {
		this.planCoverageId = planCoverageId;
	}

	@Column(name = "plan_id")
	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	@Column(name = "pcov_seq_num", nullable = false)
	public int getPcovSeqNum() {
		return this.pcovSeqNum;
	}

	public void setPcovSeqNum(int pcovSeqNum) {
		this.pcovSeqNum = pcovSeqNum;
	}

	@Column(name = "cov_plan_cd", nullable = false)
	public int getCovPlanCd() {
		return this.covPlanCd;
	}

	public void setCovPlanCd(int covPlanCd) {
		this.covPlanCd = covPlanCd;
	}

	@Column(name = "parnt_plan_cd", nullable = false)
	public int getParntPlanCd() {
		return this.parntPlanCd;
	}

	public void setParntPlanCd(int parntPlanCd) {
		this.parntPlanCd = parntPlanCd;
	}

	@Column(name = "parnt_pcov_seq_num")
	public Integer getParntPcovSeqNum() {
		return this.parntPcovSeqNum;
	}

	public void setParntPcovSeqNum(Integer parntPcovSeqNum) {
		this.parntPcovSeqNum = parntPcovSeqNum;
	}

	@Column(name = "pcov_has_dep_ind", length = 1)
	public Character getPcovHasDepInd() {
		return this.pcovHasDepInd;
	}

	public void setPcovHasDepInd(Character pcovHasDepInd) {
		this.pcovHasDepInd = pcovHasDepInd;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "lst_updt_userid", length = 20)
	public String getLstUpdtUserid() {
		return this.lstUpdtUserid;
	}

	public void setLstUpdtUserid(String lstUpdtUserid) {
		this.lstUpdtUserid = lstUpdtUserid;
	}

	@Column(name = "prod_id")
	public Integer getProdId() {
		return this.prodId;
	}

	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

}
