package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * PlanRateClass generated by hbm2java
 */
@Entity
@Table(name = "plan_rate_class")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlanRateClass implements java.io.Serializable {

	private int planRateClassId;
	private String planRateClassNm;
	private Character isDeletedInd;
	private String lstUpdtUserId;
	private Date lstUpdtDtm;

	public PlanRateClass() {
	}

	public PlanRateClass(int planRateClassId) {
		this.planRateClassId = planRateClassId;
	}

	public PlanRateClass(int planRateClassId, String planRateClassNm, Character isDeletedInd, String lstUpdtUserId,
			Date lstUpdtDtm) {
		this.planRateClassId = planRateClassId;
		this.planRateClassNm = planRateClassNm;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtUserId = lstUpdtUserId;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Id

	@Column(name = "plan_rate_class_id", unique = true, nullable = false)
	public int getPlanRateClassId() {
		return this.planRateClassId;
	}

	public void setPlanRateClassId(int planRateClassId) {
		this.planRateClassId = planRateClassId;
	}

	@Column(name = "plan_rate_class_nm", length = 100)
	public String getPlanRateClassNm() {
		return this.planRateClassNm;
	}

	public void setPlanRateClassNm(String planRateClassNm) {
		this.planRateClassNm = planRateClassNm;
	}

	@Column(name = "is_deleted_ind", length = 1)
	public Character getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(Character isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@Column(name = "lst_updt_user_id", length = 20)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

}
