package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.ebix.ifbieapp.util.CustomJacksonDateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property"

		, uniqueConstraints = @UniqueConstraint(columnNames = { "prop_cat_cd", "prop_nm" }))
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Property implements java.io.Serializable {

	private Integer id;
	private String propCatCd;
	private String propNm;
	private String propVluTxt;
	private char isDeletedInd;
	private Date lstUpdtDtm;
	private String lstUpdtUserId;

	public Property() {
	}

	public Property(String propCatCd, String propNm, char isDeletedInd, Date lstUpdtDtm) {
		this.propCatCd = propCatCd;
		this.propNm = propNm;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public Property(String propCatCd, String propNm, String propVluTxt, char isDeletedInd, Date lstUpdtDtm,
			String lstUpdtUserId) {
		this.propCatCd = propCatCd;
		this.propNm = propNm;
		this.propVluTxt = propVluTxt;
		this.isDeletedInd = isDeletedInd;
		this.lstUpdtDtm = lstUpdtDtm;
		this.lstUpdtUserId = lstUpdtUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "prop_cat_cd", nullable = false, length = 50)
	public String getPropCatCd() {
		return this.propCatCd;
	}

	public void setPropCatCd(String propCatCd) {
		this.propCatCd = propCatCd;
	}

	@Column(name = "prop_nm", nullable = false, length = 50)
	public String getPropNm() {
		return this.propNm;
	}

	public void setPropNm(String propNm) {
		this.propNm = propNm;
	}

	@Column(name = "prop_vlu_txt", length = 500)
	public String getPropVluTxt() {
		return this.propVluTxt;
	}

	public void setPropVluTxt(String propVluTxt) {
		this.propVluTxt = propVluTxt;
	}

	@Column(name = "is_deleted_ind", nullable = false, length = 1)
	public char getIsDeletedInd() {
		return this.isDeletedInd;
	}

	public void setIsDeletedInd(char isDeletedInd) {
		this.isDeletedInd = isDeletedInd;
	}

	@JsonSerialize(using = CustomJacksonDateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lst_updt_dtm", nullable = false, length = 23)
	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	@Column(name = "lst_updt_user_id", length = 50)
	public String getLstUpdtUserId() {
		return this.lstUpdtUserId;
	}

	public void setLstUpdtUserId(String lstUpdtUserId) {
		this.lstUpdtUserId = lstUpdtUserId;
	}

}
