package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReleaseDetailsT generated by hbm2java
 */
@Entity
@Table(name="release_details_t"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class ReleaseDetailsT  implements java.io.Serializable {


     private ReleaseDetailsTId id;

    public ReleaseDetailsT() {
    }

    public ReleaseDetailsT(ReleaseDetailsTId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="seqNum", column=@Column(name="seq_num", nullable=false) ), 
        @AttributeOverride(name="relVersion", column=@Column(name="rel_version", nullable=false, length=15) ), 
        @AttributeOverride(name="relDesc", column=@Column(name="rel_desc", nullable=false, length=50) ), 
        @AttributeOverride(name="relDate", column=@Column(name="rel_date", nullable=false) ), 
        @AttributeOverride(name="fileName", column=@Column(name="file_name", nullable=false, length=100) ), 
        @AttributeOverride(name="dateOfExecution", column=@Column(name="date_of_execution", nullable=false) ) } )
    public ReleaseDetailsTId getId() {
        return this.id;
    }
    
    public void setId(ReleaseDetailsTId id) {
        this.id = id;
    }




}


