package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EntityListeners;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ReleaseDetailsTId generated by hbm2java
 */
@Embeddable
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ReleaseDetailsTId implements java.io.Serializable {

	private int seqNum;
	private String relVersion;
	private String relDesc;
	private Serializable relDate;
	private String fileName;
	private Serializable dateOfExecution;

	public ReleaseDetailsTId() {
	}

	public ReleaseDetailsTId(int seqNum, String relVersion, String relDesc, Serializable relDate, String fileName,
			Serializable dateOfExecution) {
		this.seqNum = seqNum;
		this.relVersion = relVersion;
		this.relDesc = relDesc;
		this.relDate = relDate;
		this.fileName = fileName;
		this.dateOfExecution = dateOfExecution;
	}

	@Column(name = "seq_num", nullable = false)
	public int getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "rel_version", nullable = false, length = 15)
	public String getRelVersion() {
		return this.relVersion;
	}

	public void setRelVersion(String relVersion) {
		this.relVersion = relVersion;
	}

	@Column(name = "rel_desc", nullable = false, length = 50)
	public String getRelDesc() {
		return this.relDesc;
	}

	public void setRelDesc(String relDesc) {
		this.relDesc = relDesc;
	}

	@Column(name = "rel_date", nullable = false)
	public Serializable getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Serializable relDate) {
		this.relDate = relDate;
	}

	@Column(name = "file_name", nullable = false, length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "date_of_execution", nullable = false)
	public Serializable getDateOfExecution() {
		return this.dateOfExecution;
	}

	public void setDateOfExecution(Serializable dateOfExecution) {
		this.dateOfExecution = dateOfExecution;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseDetailsTId))
			return false;
		ReleaseDetailsTId castOther = (ReleaseDetailsTId) other;

		return (this.getSeqNum() == castOther.getSeqNum())
				&& ((this.getRelVersion() == castOther.getRelVersion()) || (this.getRelVersion() != null
						&& castOther.getRelVersion() != null && this.getRelVersion().equals(castOther.getRelVersion())))
				&& ((this.getRelDesc() == castOther.getRelDesc()) || (this.getRelDesc() != null
						&& castOther.getRelDesc() != null && this.getRelDesc().equals(castOther.getRelDesc())))
				&& ((this.getRelDate() == castOther.getRelDate()) || (this.getRelDate() != null
						&& castOther.getRelDate() != null && this.getRelDate().equals(castOther.getRelDate())))
				&& ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null
						&& castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())))
				&& ((this.getDateOfExecution() == castOther.getDateOfExecution())
						|| (this.getDateOfExecution() != null && castOther.getDateOfExecution() != null
								&& this.getDateOfExecution().equals(castOther.getDateOfExecution())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeqNum();
		result = 37 * result + (getRelVersion() == null ? 0 : this.getRelVersion().hashCode());
		result = 37 * result + (getRelDesc() == null ? 0 : this.getRelDesc().hashCode());
		result = 37 * result + (getRelDate() == null ? 0 : this.getRelDate().hashCode());
		result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result + (getDateOfExecution() == null ? 0 : this.getDateOfExecution().hashCode());
		return result;
	}

}
