package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Revocable generated by hbm2java
 */
@Entity
@Table(name="revocable"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class Revocable  implements java.io.Serializable {


     private BigDecimal revocableId;
     private CaseClientAddressDetails caseClientAddressDetails;
     private CaseClientMap caseClientMap;
     private String name;
     private Character isRevocableInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public Revocable() {
    }

	
    public Revocable(CaseClientMap caseClientMap, String lstUpdtUserId, Date lstUpdtDtm) {
        this.caseClientMap = caseClientMap;
        this.lstUpdtUserId = lstUpdtUserId;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public Revocable(CaseClientAddressDetails caseClientAddressDetails, CaseClientMap caseClientMap, String name, Character isRevocableInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.caseClientAddressDetails = caseClientAddressDetails;
       this.caseClientMap = caseClientMap;
       this.name = name;
       this.isRevocableInd = isRevocableInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="revocable_id", unique=true, nullable=false, scale=0)
    public BigDecimal getRevocableId() {
        return this.revocableId;
    }
    
    public void setRevocableId(BigDecimal revocableId) {
        this.revocableId = revocableId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_client_address_details_id")
    public CaseClientAddressDetails getCaseClientAddressDetails() {
        return this.caseClientAddressDetails;
    }
    
    public void setCaseClientAddressDetails(CaseClientAddressDetails caseClientAddressDetails) {
        this.caseClientAddressDetails = caseClientAddressDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="case_client_map_id", nullable=false)
    public CaseClientMap getCaseClientMap() {
        return this.caseClientMap;
    }
    
    public void setCaseClientMap(CaseClientMap caseClientMap) {
        this.caseClientMap = caseClientMap;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="is_revocable_ind", length=1)
    public Character getIsRevocableInd() {
        return this.isRevocableInd;
    }
    
    public void setIsRevocableInd(Character isRevocableInd) {
        this.isRevocableInd = isRevocableInd;
    }

    
    @Column(name="lst_updt_user_id", nullable=false, length=20)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


