package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EntityListeners;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SiPropertyId generated by hbm2java
 */
@Embeddable
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SiPropertyId implements java.io.Serializable {

	private String propCatCd;
	private String propNm;

	public SiPropertyId() {
	}

	public SiPropertyId(String propCatCd, String propNm) {
		this.propCatCd = propCatCd;
		this.propNm = propNm;
	}

	@Column(name = "prop_cat_cd", nullable = false, length = 50)
	public String getPropCatCd() {
		return this.propCatCd;
	}

	public void setPropCatCd(String propCatCd) {
		this.propCatCd = propCatCd;
	}

	@Column(name = "prop_nm", nullable = false, length = 50)
	public String getPropNm() {
		return this.propNm;
	}

	public void setPropNm(String propNm) {
		this.propNm = propNm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SiPropertyId))
			return false;
		SiPropertyId castOther = (SiPropertyId) other;

		return ((this.getPropCatCd() == castOther.getPropCatCd()) || (this.getPropCatCd() != null
				&& castOther.getPropCatCd() != null && this.getPropCatCd().equals(castOther.getPropCatCd())))
				&& ((this.getPropNm() == castOther.getPropNm()) || (this.getPropNm() != null
						&& castOther.getPropNm() != null && this.getPropNm().equals(castOther.getPropNm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPropCatCd() == null ? 0 : this.getPropCatCd().hashCode());
		result = 37 * result + (getPropNm() == null ? 0 : this.getPropNm().hashCode());
		return result;
	}

}
