package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="state"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class State  implements java.io.Serializable {


     private String stateCd;
     private String countryCd;
     private String stateDesc;
     private char isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public State() {
    }

	
    public State(String stateCd, String countryCd, String stateDesc, char isDeletedInd, Date lstUpdtDtm) {
        this.stateCd = stateCd;
        this.countryCd = countryCd;
        this.stateDesc = stateDesc;
        this.isDeletedInd = isDeletedInd;
        this.lstUpdtDtm = lstUpdtDtm;
    }
    public State(String stateCd, String countryCd, String stateDesc, char isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.stateCd = stateCd;
       this.countryCd = countryCd;
       this.stateDesc = stateDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="state_cd", unique=true, nullable=false, length=2)
    public String getStateCd() {
        return this.stateCd;
    }
    
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }

    
    @Column(name="country_cd", nullable=false, length=3)
    public String getCountryCd() {
        return this.countryCd;
    }
    
    public void setCountryCd(String countryCd) {
        this.countryCd = countryCd;
    }

    
    @Column(name="state_desc", nullable=false, length=50)
    public String getStateDesc() {
        return this.stateDesc;
    }
    
    public void setStateDesc(String stateDesc) {
        this.stateDesc = stateDesc;
    }

    
    @Column(name="is_deleted_ind", nullable=false, length=1)
    public char getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(char isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", nullable=false, length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


