package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UnemploymentStatus generated by hbm2java
 */
@Entity
@Table(name="unemployment_status"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class UnemploymentStatus  implements java.io.Serializable {


     private String unempolymentStatusCd;
     private String unempolymentStatusDesc;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public UnemploymentStatus() {
    }

	
    public UnemploymentStatus(String unempolymentStatusCd, String unempolymentStatusDesc) {
        this.unempolymentStatusCd = unempolymentStatusCd;
        this.unempolymentStatusDesc = unempolymentStatusDesc;
    }
    public UnemploymentStatus(String unempolymentStatusCd, String unempolymentStatusDesc, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.unempolymentStatusCd = unempolymentStatusCd;
       this.unempolymentStatusDesc = unempolymentStatusDesc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="unempolyment_status_cd", unique=true, nullable=false, length=40)
    public String getUnempolymentStatusCd() {
        return this.unempolymentStatusCd;
    }
    
    public void setUnempolymentStatusCd(String unempolymentStatusCd) {
        this.unempolymentStatusCd = unempolymentStatusCd;
    }

    
    @Column(name="unempolyment_status_desc", nullable=false, length=50)
    public String getUnempolymentStatusDesc() {
        return this.unempolymentStatusDesc;
    }
    
    public void setUnempolymentStatusDesc(String unempolymentStatusDesc) {
        this.unempolymentStatusDesc = unempolymentStatusDesc;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=50)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


