package com.ebix.ifbieapp.model;
// Generated Mar 23, 2018 11:11:12 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisaType generated by hbm2java
 */
@Entity
@Table(name="Visa_Type"
    ,schema="dbo"
    ,catalog="life_eapp"
)
public class VisaType  implements java.io.Serializable {


     private String visaTypCd;
     private String visaTypDsc;
     private Character isDeletedInd;
     private String lstUpdtUserId;
     private Date lstUpdtDtm;

    public VisaType() {
    }

	
    public VisaType(String visaTypCd) {
        this.visaTypCd = visaTypCd;
    }
    public VisaType(String visaTypCd, String visaTypDsc, Character isDeletedInd, String lstUpdtUserId, Date lstUpdtDtm) {
       this.visaTypCd = visaTypCd;
       this.visaTypDsc = visaTypDsc;
       this.isDeletedInd = isDeletedInd;
       this.lstUpdtUserId = lstUpdtUserId;
       this.lstUpdtDtm = lstUpdtDtm;
    }
   
     @Id 

    
    @Column(name="Visa_typ_cd", unique=true, nullable=false, length=8)
    public String getVisaTypCd() {
        return this.visaTypCd;
    }
    
    public void setVisaTypCd(String visaTypCd) {
        this.visaTypCd = visaTypCd;
    }

    
    @Column(name="Visa_typ_dsc", length=20)
    public String getVisaTypDsc() {
        return this.visaTypDsc;
    }
    
    public void setVisaTypDsc(String visaTypDsc) {
        this.visaTypDsc = visaTypDsc;
    }

    
    @Column(name="is_deleted_ind", length=1)
    public Character getIsDeletedInd() {
        return this.isDeletedInd;
    }
    
    public void setIsDeletedInd(Character isDeletedInd) {
        this.isDeletedInd = isDeletedInd;
    }

    
    @Column(name="lst_updt_user_id", length=20)
    public String getLstUpdtUserId() {
        return this.lstUpdtUserId;
    }
    
    public void setLstUpdtUserId(String lstUpdtUserId) {
        this.lstUpdtUserId = lstUpdtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lst_updt_dtm", length=23)
    public Date getLstUpdtDtm() {
        return this.lstUpdtDtm;
    }
    
    public void setLstUpdtDtm(Date lstUpdtDtm) {
        this.lstUpdtDtm = lstUpdtDtm;
    }




}


